### ISSUE TITLE
SeanA_FinalProjectProposal

### ISSUE THREAD

**Issue by sabbott7** [valencia-cop1000-201620/final-project#10]
### Name
Sean Abbott

### Proposed Project Description
In this project I am trying to build a one-player version of the classic board game Battleships ! 
In this version of the game, there will be a single ship hidden in a random location on a 5 x 5 grid.
The player will have a limited number of guesses to try to sink the ship. Each miss (or turn) will be marked by an X.

Battlestations ! Battlestations ! Battlestations !
O O O O O
O O O O O
O O O O O
O O O O O
O O O O O
Guess Row:3
Guess Col:3
You missed !
Fire 1 out of 4.
O O O O O
O O O O O
O O O O O
O O O X O
O O O O O
Guess Row:4
Guess Col:2
You missed !
Fire 2 out of 4.
O O O O O
O O O O O
O O O O O
O O O X O
O O X O O
Guess Row:
Guess Col:

### Connecting Concepts
To build this game I will use knowledge of flow Control/loops (Chap.2), functions (Chap.3) and lists (Chap.4)

### Timing
By Tue 19th Apr 2016  - to have feedback from a few classmates
By Wed 20th Apr 2016 - to get sign off for approval

### Asking for...
Are my timescales realistic ? Have I missed anything ?

**Comment by BobbyGatlin** [comment]
It sounds like a good project. I love Battleship. How long do you expect it to take for you to do the coding for the project?

**Comment by elisenharper** [comment]
Sounds like a cool idea! How do you plan to represent the ship?

**Comment by xyngabo** [comment]
Sounds like a fun project, good luck!

**Comment by Mr-Edwin** [comment]
Would the interface be handled kind of like the tic tac toe one or are you planning something different?

**Comment by mmarchetti2** [comment]
So far, the main thing I'd think of is how would you go about the interface? Battleship is a pretty intricate game, but I think if you implement the techniques we learned from the Tic-Tac-Toe game we programmed, you'd be able to get a great head-start.

**Comment by halfaro1** [comment]
@sabbott7 I would echo what everyone else here is saying and think about what the interface would look like. If you'd like, you can edit your original post and show a simulated interaction between the player and the computer so we can see what you can expect.

**Comment by sabbott7** [comment]
@BobbyGatlin I anticipate to have done a 1st/2nd draft done by Tue 26 Apr 2015, and code to include: function blocks, if else/elif blocks with comments.

**Comment by sabbott7** [comment]
@elisenharper The ship will be represented by a row and col position in the grid randomly selected by importing the random library. Win or Lose at the end the ships co-ordinates will be revealed and output to the player via the screen.

**Comment by sabbott7** [comment]
@mmarchetti2 for the interface I initialize a board (5 x 5 grid) then output it to the screen. The player selects a row and column position within the board, i.e. rows (0 to 4) and cols (0 to 4) - which then updates for each missed turn with an 'X'.

**Comment by sabbott7** [comment]
@Mr-Edwin..Yes but less opportunity but more "cut-and-thrust" !

**Comment by sabbott7** [comment]
@halfaro1 for the interface I initialize a board (5 x 5 grid) then output it to the screen. The player selects a row and column position within the board, i.e. rows (0 to 4) and cols (0 to 4) - which then updates for each missed turn with an 'X'. Win or Lose the ships co-ordinates are revealed at the end.

**Comment by halfaro1** [comment]
@sabbott7 awesome, you have my 👍 to begin implementing :)

**Comment by rtran4** [comment]
It's cool how you worked a depiction for us! It looks very organized and I can't see what you're going to do with it. Good luck!
