### ISSUE TITLE
Final Project Proposal: mmarchetti2

### ISSUE THREAD

**Issue by mmarchetti2** [valencia-cop1000-201620/final-project#11]
### Name
Matthew Aaron Marchetti

### Proposed Project Description
I would like to make a program that can search through a .txt file for a phone number. The phone numbers in the text file could have different forms, such as (XXX) XXX-XXXX or +1XXXXXXXXXX. I would have a regex for each form, and the program would search for all of them in the file and return them. Also, if I can implement the phone number feature in time, I'd like to add other features as well, such as searching for a time or 4-digit code. As of right now, I'll only be doing phone numbers in .txt files, but I hope to widen the range of the code to include .pdfs as well as at least one more text file.

### Connecting Concepts
Well, from my ideas on how I will code it, I would say that it will combine the topics of Chapter 2 - Flow Control, Chapter 3 - Functions, Chapter 7 - Regexes,  Chapter 8 - Reading and Writing Files, and Chapter 13 - Working with PDFs. :)

### Timing
I know I am submitting this a bit late, but if I can get approval by the 20th, I should be able to code this on time. First off, by the 23 I expect to be done with all the regexes and settings. Secondly, I would like to get the reading files portion done by the 25 at the very latest. From then on, I would continue to test it and add any other necessary features.

### Ask for...
Do you think this proposal is complicated enough? I thought it would be a good combination of several topics that we learned, but I'm not sure.

**Comment by BobbyGatlin** [comment]
I believe that this project could definitely be complicated enough. What document formats do you want this to be able to search through?

**Comment by elisenharper** [comment]
I was wondering the same thing... which document format are you working with?

**Comment by mmarchetti2** [comment]
Well, I was just thinking docx and pdf, do you have any other ideas?

**Comment by halfaro1** [comment]
@mmarchetti2 definitely complicated enough, in fact I'm going to suggest you narrow it down a little. First, I'd settle down on one particular document format (either DOCX or PDF are both fine, you could also go with something like TXT if you'd like). Second, I'd recommend on just making your program find one thing (like a phone number). That's hard enough as you'd have to figure out how to open and traverse the document, and build and execute a search with the regex. If you can get this working in time, you could always add in extra features but let's not make it harder than it has to on yourself. What are your 💭 ?

**Comment by sabbott7** [comment]
.How will you handle the different phone formats e.g XXX-XXX-XXXX or XXXXXXXXXX or +1XXXXXXXXX etc.

**Comment by mmarchetti2** [comment]
Okay, for the time being I'll just try to do DOCX for now. I'm just thinking, if I can get DOCX to work, it shouldn't be too hard just adding another document type. And sabbott7, thanks for the feedback. I hadn't really thought of those formats, but I'm pretty sure I can make allowances for those. Maybe even make separate regexes for each type, and it will search the document for all of them.

**Comment by halfaro1** [comment]
@mmarchetti2 perfect, thanks for the clarification! Please edit your original post and then let me know in a comment. Once you do that I'll give the green light for implementation.

**Comment by mmarchetti2** [comment]
Okay, by the way, I'm having quite a bit of trouble installing python-docx, so I'll just stick with .txt files for now. :)

**Comment by halfaro1** [comment]
@mmarchetti2 awesome. I think this project is good to go the way it is with the possible upgrades you described if you finish in time. For your design document, please focus on showing examples of all the types of phone numbers that would/wouldn't be recognized by your program and also an explanation of what will happen with the found patterns. Will they be returned to the screen? Or saved in another text file?
