### ISSUE TITLE
Bobbygatlin's Final Project Proposal

### ISSUE THREAD

**Issue by BobbyGatlin** [valencia-cop1000-201620/final-project#12]
### Name
Bobby Gatlin

### Proposed Project Description
I'd like to build my own text based adventure game with a horror theme. It will be similar to old school text based adventures such as Zork or Hitchhiker's guide on a much smaller scale. I plan on starting in an old Cabin in the Woods where the Deadites have been released once again by the powers of the evil Necronomicon. You play our hero, Ashley  J. Williams. Ash for short. You must navigate through the old cabin and find the Necronomicon to once again seal away the Deadites and save the world from the power of The Evil Dead.

### Connecting Concepts
A lot of topics will be needed for this project such as strings, variables, if/else statements, print, list, and integers.

### Timing
It will probably take me 6 to 8 hours to implement the project. 

### Asking for...
I have a pretty good idea of how to accomplish this but if anyone has any tips I'll definitely be very receptive.

**Comment by xyngabo** [comment]
Good luck!  I considered doing something like this for my project.

**Comment by Mr-Edwin** [comment]
I think this is a cool idea. I think if you just have it kind of like the computer is telling a story and the user is part of it and along the story the computer asks some questions on what to do or how to go about certain situations and depending on what happens the story line changes.

**Comment by xyngabo** [comment]
Maybe you could be able to pick up items along the way, that you need to get passed certain parts..?

**Comment by halfaro1** [comment]
@BobbyGatlin awesome idea! Love it! Please start by modifying your original post with some of the material you'll use for the text adventure game. What is the gameplay going to be like? You can build this in text before you do any programming at all.

**Comment by pvo4** [comment]
I love your idea! Can you die in the game by making a bad choice? If so, do you restart from the beginning?

**Comment by BranLWill** [comment]
Great Idea! Would it be similar to Oregon trail but text based with companions in it that can die if you choose the wrong choices?

**Comment by BobbyGatlin** [comment]
I'm actually planning on making it a bit more simple than that. You can't die. I would definitely never kill off Ash. As for items I'm pretty sure I'm only gonna make one. The main goal will be finding the Necronomicon which will be hidden randomly in one of the six rooms of the cabin. You'll navigate the different rooms by way of the cardinal points, NESW. There will be a good amount of text involved though.

**Comment by Chummel** [comment]
I really like this idea. Zork was always fun so I'd think that this seems fun as well. I'm looking forward to seeing what you have to code!

**Comment by halfaro1** [comment]
@BobbyGatlin great, this is approved 👍 but please make sure your design document contains the meat of the game. Since it's text based, you should be able to show what the different levels/options are, a map of where the user would be at any given point and all the possible points in the game, and text responses.

**Comment by halfaro1** [comment]
@BobbyGatlin I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
