### ISSUE TITLE
Mr-Edwin's Final Project Proposal

### ISSUE THREAD

**Issue by Mr-Edwin** [valencia-cop1000-201620/final-project#13]
### Name
Edwin
### Proposed Project Description
I will make a password generator were a person can choose what their password needs to have and even default "strengths". The person just chooses one or multiple options and the generator generates a random password. 
Hello, how many characters do you want your password to be?

User Inputs: 6

Hello, what would you like your password to consist of?
1. Uppercase
2. Lowercase
3. Symbols
4. Numbers
5. Default Strength

User Chooses: 1, 2, 4

Computer Output: Fv2eY1
The password has been copied to your clipboard!

### Connecting Concepts
This project will cover mostly chapter six. IT will have to do a lot with dictionaries and strings and also flow controls.

### Timing
I know I am a little late on my proposal but as soon as I get this approved I will begin on the getting of the accounts and passwords after that I will work on the "user interface"(All text based).

### Asking for...
Is this project complicated enough? Should I add/remove something?

**Comment by xyngabo** [comment]
Will the passwords be encrypted?

**Comment by halfaro1** [comment]
@Mr-Edwin thanks for the proposal! I don't think we've covered password protection or encrypting so I want to make sure you have the resources you need to succeed. You'll have to read up a little bit on encryption so that your passwords aren't just sitting in a plain text file on your computer. Might I suggest instead a password generator program? What if you build a program that will generate a password based on the criteria the user desires? Uppercase letters, lowercase letters, numbers, symbols, etc? If you're successful, then you might want to "upgrade" the program later so that it has the ability to store passwords as well.

**Comment by pvo4** [comment]
@Mr-Edwin I remember reading a little about encrypting in chapter 13, but that was for PDFs. I'm not sure how you would go password protecting your program, but I think it would be a cool proposal if your able to pull it off. I have a lot of usernames and passwords for different websites and a program like this would be very helpful.

**Comment by Mr-Edwin** [comment]
Ok I will do that then. Change it from password storing to password generating but I will look into encrypting files. Thank You

**Comment by halfaro1** [comment]
@Mr-Edwin perfect thanks! Go ahead and edit your original post so it shows the new proposal and include the options your program will allow and some sample passwords that it will create as a result.

**Comment by Mr-Edwin** [comment]
@halfaro1 Ok I updated it with kind of what I had in mind.

**Comment by halfaro1** [comment]
@Mr-Edwin great! This is approved. As you move on to part 2 of the project, start by filling out your design document and in that design include the examples we discussed here and start thinking about how you'll implement this.

**Comment by halfaro1** [comment]
@Mr-Edwin I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
