### ISSUE TITLE
pvo4: Final Project Proposal

### ISSUE THREAD

**Issue by pvo4** [valencia-cop1000-201620/final-project#14]
### Name
Phillip Vo

### Proposed Project Description

For my final project I would like to recreate a game of blackjack. Growing up my family would get together and play different card games. Reminiscing and trying to think of an idea, blackjack instantly came to mind as a project I would like to see myself accomplish. The overall purpose of the program is to create a little game to pass the time. Below is an outline of what I would like my program to do:

- the program is able to play a simple game of blackjack between the user and the computer (dealer)

- either give the dealer a random number between 15-21 or make an A.I. that can hit or stay (the latter sounds difficult and way out of my knowledge)

- allow the user to hit or stay

- be able to differentiate when the player bust, lose or win

- Give the player a set amount of chips/credit

- Allow the player to bet on the amount of chips 

- add or subtract the chips

- When the player runs out of chips, game over

### Connecting Concepts

The project will cover at least chapters 1-5: basics, flow control, functions, lists, dictionaries and structuring data. 

### Timing

After getting the thumbs up, the program should take me a couple of days to do or more because of my schedule. I plan on working on it little by little and on my off days focus my time and efforts on it until the deadline.

### Asking for...

I'm open to any feed back. Is this game something I can make within the week? Any suggestions on how to make a A.I that can make it's own decision to hit or stay? What other parameters should I put in the game?

**Comment by halfaro1** [comment]
@pvo4 I love this idea -- in fact, it's been a final project I've given my students in the past ;)
The main issue I ran into when having students create this program, is the model of the card deck. How will you represent the card deck? What data structure will you use (lists, dictionaries, etc?). Will this be text-based or somehow utilize graphics?

**Comment by pvo4** [comment]
Utilizing the knowledge we've learned I intended it to be text based. Graphics would be an awesome feature, but I'm not sure on how to implement that yet. I was going to use dictionaries to store the values of the cards.

**Comment by pvo4** [comment]
@halfaro1 sorry, forgot to @ you about.

**Comment by halfaro1** [comment]
@pvo4 great, this is approved. Please make sure you spend some time on your design document to figure out how you'll represent the card deck in Python, and thinking about what the logic in your program will be to achieve each one of the things you want to do. I'd also suggest you implement this in iterations. So, build a *very simple* program first, that is capable of performing one thing (such as shuffling a deck of cards), then start adding on to it (shuffle a deck of cards + deal one card to a player), add some more (shuffle cards + deal one card + deal enough cards for the dealer). Do you understand? This way, if you get stuck you can always work from the last increment that was successful, or so you can submit a "working" version even if it's not everything you want to do. In your design document, also specify at least 2 or 3 different increments that you could turn in if you're not able to have a fully functional program when it's all said and done.

**Comment by pvo4** [comment]
@halfaro1 yes sir, thank you for the advice.

**Comment by rtran4** [comment]
This is a great idea for a project! I thought of doing blackjack as well but I was scared to attempt to code it.
