### ISSUE TITLE
Limbert Desir Final Project

### ISSUE THREAD

**Issue by Ldesir05** [valencia-cop1000-201620/final-project#15]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

Limbert Desir Final Project.

### Name

Limbert Desir.

### Proposed Project Description

For my Final project, at work i am left with the boring task of editing a CSV file. Which is downloaded from a Sprint portal. Then i have to edit all the files on that sheet or clean up and the final result ending with three columns. First column is the phone numbers, Second column is the names and the Third column is the total charge for the month.I plan on writing a script to open a browser. Navigate to through the portal, Download the CSV file. Grab the information and create a new Excel file with the final results.

### Connecting Concepts
What chapters/topics will this project allow you to practice? A good final project will cover at least 2 distinct topics from class. 

I plan on using the chapter 11,12 and 14 to help me accomplish this

### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.

i believe that this would take me a week to complete or completed on the 26th or no later than the 27th.

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?

Any feedback would be great, I am putting myself to the challenge.

**Comment by halfaro1** [comment]
@Ldesir05 this seems like a perfect fit for the final project! From your description, I'm a little unclear on what the initial file looks like and what the final product would be. Could you post some examples? You can make them up so you're not posting work-sensitive things, or you can post some actual files you use and edit out any data that's sensitive. I'm more interested in seeing the two formats.

**Comment by Ldesir05** [comment]
@halfaro1 where would i be posting the file and after reading you response i noticed i was using some work related files so i would have to create a file of my own

**Comment by DanielCowman** [comment]
Seeing as you're at work I would assume the portal you pull the CSV file from needs authentication to access it, be careful not to expose any usernames or passwords when submitting this project.

**Comment by larawillson** [comment]
@Ldesir05 What a great idea! I have a bunch of those monotonous tasks that I have to do at work as well, so I can understand how useful it would be to have a program to aid with certain tasks. Good Luck!

**Comment by Ldesir05** [comment]
@DanielCowman i am going to change this up slightly i am going to create a random generator to create names and phone numbers and use that with a template that i am going to create. i plan on having it download the template from a google drive or a shared portal

**Comment by Ldesir05** [comment]
@larawillson thank you

**Comment by Ldesir05** [comment]
@halfaro1 for privacy i am going to try to script a random generator to create names and phone numbers on a template with usage etc

**Comment by halfaro1** [comment]
@Ldesir05 well, what I meant was that I wanted to see 2 sample files (posted to this issue): (1) would be an example of what the format of the files is as you get them, and (2) would be what the file would look like when your program is finished with it. I think your original idea is fantastic and you should continue to do that, but it's ultimately up to you. I think it might be more complicated (and not as useful) to create a random generator of names and numbers. Does that make sense?

**Comment by Ldesir05** [comment]
@halfaro1 getting the file together so i can post it, Also changing the random generator going to create the name myself

**Comment by Ldesir05** [comment]
@halfaro1 the file titled sprint1 is the file being downloaded and the file titled Results is the final product
[results.xlsx](https://github.com/valencia-cop1000-201620/final-project/files/230169/results.xlsx)
[sprint1.xlsx](https://github.com/valencia-cop1000-201620/final-project/files/230168/sprint1.xlsx)

**Comment by Ldesir05** [comment]
@halfaro1 for privacy i created dummy names and dummy numbers

**Comment by halfaro1** [comment]
@Ldesir05 perfect. I think this gives me a perfect idea of what you're trying to accomplish and I'm comfortable approving this 👍

**Comment by halfaro1** [comment]
@Ldesir05 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
