### ISSUE TITLE
rpineda1's Final Project Proposal

### ISSUE THREAD

**Issue by rpineda1** [valencia-cop1000-201620/final-project#16]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Ricardo Pineda

### Proposed Project Description
The project I want to propose  for the final is pong. its has not only AI, but it also needs a tracking system, and a collision source. the reason why I chose pong is because it covers a lot of chapters we looked into in this semester. it's not the easiest program, but it is manageable. the only thing that is needed outside of the book is probably movement, but and needed code I would fill in for the programmer.

### Connecting Concepts
The needed chapters are CH 3, 4, 6, 14.

### Timing
by 4/21 I would complete the window for the game, by 4/23, I would make the ball and lines/paddles by 4/24 I would make the collision and AI, and finally by the 25th of April I will make the scoring.

### Asking for...
small solutions if I'm unable to debug.

**Comment by halfaro1** [comment]
@rpineda1 thanks for the great suggestion. Unfortunately, we haven't covered anything about animation or constant motion on the screen, so I don't want to set you up for failure. I think you have two avenues you can pursue: (1) you can try to modify this idea so you're using a game that is turn-based and so you can implement easier through text, or (2) you can look for ways to perform animation and motion in Python, and decide to implement that. If you decide to do (2), I'd like you to post the results of your research here including what Python libraries you found, examples of those libraries in use, and updated timeline for implementation. Let me know your thoughts.

**Comment by halfaro1** [comment]
@rpineda1 how are you doing on this? the final project is due soon and I'd like you to move forward

**Comment by halfaro1** [comment]
@rpineda1 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
