### ISSUE TITLE
Final project proposal

### ISSUE THREAD

**Issue by mviruet2** [valencia-cop1000-201620/final-project#17]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Meralys Viruet

### Proposed Project Description
I am a dog person.  For my final project I want to build a program (based on reaserch and what I have learned all my life as a dog lover) that will make some simple questions and it will tell you a few breeds of dogs you should get based on your answers. Sometimes is difficult to to know what breed of dog is best for you. There are some websites that based on the answers you give it tells you the breed of dog you should get, I think they don't work (I took it before I adopted my dog and now he loves more my boyfriend than me). I would like to make it much better. I have studied dogs and cats and I now most of their needs and what they like. Larger dogs are very active and playful and need owners with that can give them the attention they need. Medium dogs are somewhat active as larger dogs and they can be comfortable in a small apartments like smaller dogs. Smaller dogs can are not as active and the bigger dogs. I have had many dog in my life and I love animals and like to see them happy.

### Connecting Concepts
Chapter #3, #5

### Timing
It will probably take me a couple of days up to 2 days. 

### Asking for...
Is this too simple for a final project? Please give some feedback. It will be so helpful.

**Comment by halfaro1** [comment]
@mviruet2 awesome idea! It's not too simple -- it's just right. I'd like to see you think about what those questions would be and what breed they would yield. Edit your original post with that information and then let us know in a comment. Oh yeah, and cute pictures of puppies wouldn't hurt 🐶

**Comment by shuroq** [comment]
@mviruet2 Great idea. I am a dog person too. When I first wanted to have a dog I was confused about what breed is the best for me. After  long research, I got the pomeranian puppy and its cuuuuuute. About your programme, I think it would be helpful if you ask about the age and the gender. Let me if you need any help. 
Good luck

**Comment by BranLWill** [comment]
Love this idea! Would it have all the different types of breads or just a select few.

**Comment by DanielCowman** [comment]
Hey, awesome idea! maybe you could link to the wikipedia article for the breed chosen.

**Comment by Chummel** [comment]
Great idea! I think it should link to online articles that would give more information on that breed of dog once it's determined what the user would like.

**Comment by mviruet2** [comment]
@shuroq thanks for offering your help
@BranLWill only a few breeds
@DanielCowman , @Chummel thanks! I will see what I can do

**Comment by nhatnam113** [comment]
Great idea my friend! I'm looking for a dog too and It's better if you have some pictures.

**Comment by halfaro1** [comment]
@mviruet2 how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by mviruet2** [comment]
@halfaro1 I'm doing it like a quiz. For the final result I'm gonna instead of giving a specific breed I'm going to divided in three categories, big dogs, medium dog, and small dog.

**Comment by halfaro1** [comment]
@mviruet2 ok, can we see what the quiz questions are?

**Comment by mviruet2** [comment]
Do you like dogs?
Have you ever owned a dog?
Do you live in an apartment?
Do you exercise regularly?
Do you have time to walk/play with a dog?
Do you have a dog park near where you live?
Are you 20 or older?
Would you let a dog sleep in your bed? 
Do you want a low maintenance dog? 
Are you looking for a cuddles buddy?

**Comment by halfaro1** [comment]
@mviruet2 and how does someone's response correspond to a breed?

**Comment by mviruet2** [comment]
Based on my research of the dogs needs I'm going to make multiple possible response and i will assign a group of dogs to choose on

**Comment by halfaro1** [comment]
@mviruet2 I need to see that research as part of this proposal.

**Comment by mviruet2** [comment]
I have the program ready. @halfaro1

**Comment by halfaro1** [comment]
@mviruet2 I'd still like to know what the responses were...

**Comment by mviruet2** [comment]
@halfaro1 The responses were that bigger dogs need more attention, space, and have more evergy than smaller dogs.

**Comment by halfaro1** [comment]
@mviruet2 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
