### ISSUE TITLE
gkaja14

### ISSUE THREAD

**Issue by gkaja14** [valencia-cop1000-201620/final-project#18]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Kajenthini Sathiyaseelathevan

### Proposed Project Description
I am thinking of the Bagels game. Bagels is a deduction game you can play with a friend. Your friend thinks up a random 3-digit number with no repeating digits, and you try to guess what the number is. After each guess, your friend gives you three types of clues, for example

Bagels – None of the three digits you guessed is in the secret number.
Pico – One of the digits is in the secret number, but your guess has the digit in the wrong place.
Fermi – Your guess has a correct digit in the correct place.
You can get multiple clues after each guess. If the secret number is 456 and your guess is 546 the clues would be “fermi pico pico”. The 6 provides “fermi” and the 5 and 4 provide “pico pico”.

### Connecting Concepts
I think this game covers the loop, flow control, lists and dictionary. 

### Timing
I think I can finish this on time before 27th April. 

### Asking for...
I am open to any feedback.

**Comment by halfaro1** [comment]
@gkaja14 awesome idea! I'd like to see some examples of gameplay

**Comment by ryby6969** [comment]
That sounds rather fun. So this would be a 2 person game or would you program it with the computer selecting the number and giving out the responses?

**Comment by gkaja14** [comment]
I am going to program it with the computer.

**Comment by gkaja14** [comment]
As an example, lets say that you thought of the secret number 489.
Guess 1: 362     Bagel — no digit is correct.
Guess 2: 820     Pico — the 8 is in the wrong place.
Guess 3: 418      Pico Fermi — the 8 is in the wrong place, the 4 is in the correct place.
Guess 4: 518     Pico — the 8 is in the wrong place.
Guess 5: 487     Fermi Fermi — the 4 and 8 are in the correct place.
Guess 6: 489     Fermi Fermi Fermi — all digits are in the correct place, and it allow 10 guesses and after 10th guess, and if you didn't get the correct number the computer will give us the number it is thinking.

**Comment by halfaro1** [comment]
@gkaja14 perfect - approved. Thank you 👍

**Comment by JoshuaRi** [comment]
I like the idea of being able to play with a friend or the computer is there anyway you can have more then two players?

**Comment by halfaro1** [comment]
@gkaja14 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
