### ISSUE TITLE
Christopher Pelaez final project proposal.

### ISSUE THREAD

**Issue by chrispelaez** [valencia-cop1000-201620/final-project#19]
### Name
Christopher Pelaez

### Proposed Project Description
I would like to create a rock paper scissors game to be played between a user and the computer.
In the game I would like to create easter eggs to offer more variety than just the basic 3 options.
Hidden options may include "light saber vs Laser blaster vs ion grenade " but finding these hidden gems will be up to the player. Each game will be between 5 to 10 rounds. If there is a draw between the user and the computer then there will be a Bonus round referred to as a "Joust" ( The rock, paper, scissors equivalent of a sudden death.)

### Connecting Concepts
This project will cover concepts from chapters 1-5

### Timing
The program if approved will be submitted no later then next Friday the 22 I have most of my assignments finished from my other classes and can dedicate as much time as need to refine and submit the completed version on Wednesday the 27

### Asking for...
Any and all ideas will be welcomed when it comes to hidden easter eggs you would like to see appear in the final build of the game.

**Comment by BranLWill** [comment]
I like your idea. I'm curious on how your going to implement Easter eggs in it.

**Comment by larawillson** [comment]
@chrispelaez Great idea! I like that you're taking it farther with the Joust and the hidden options. Can't wait to see the end result. Good Luck!

**Comment by halfaro1** [comment]
Good idea, @chrispelaez. To get it ready for approval, please think about what the gameplay would look like, and post an example interaction between player and computer. It would also help to outline all the possible outcomes, including easter 🍳

**Comment by chrispelaez** [comment]
the gameplay will be based on user inputs for example 
while rps_user == rps[0]:
        if rps_ai == rps[0]:
            print('computer picked rock. Tie game!')
            break
the code will run all avaliable options in the rock, paper scissors format
Ideas for easter eggs will include lightsaber,blaster,ion. Fire ,water ,earth, (earth beats fire,water beats earth,fire beats water. I plan on using list in order to have the computer use the available options although I am having trouble trying to figure out how to create a sudden death mode for the game.

**Comment by chrispelaez** [comment]
I have a demo for the game that just runs the rock paper scissor function. unfortunately I miss read your comment and didn't submit the information you were looking for till today(sorry about that!) seeing that I have not been approved yet I would like to submit my demo which will give a more clearer idea of what I am trying to do. I have to go to work now unfortunately. If approved I can submit the demo as a pull request so that i can ask and receive feed back(which I really need)

**Comment by halfaro1** [comment]
@chrispelaez alright, I'm OK with you moving forward and I appreciate that you've continued to do work while you're waiting for approval 👍

**Comment by halfaro1** [comment]
@chrispelaez I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
