### ISSUE TITLE
shuroq's Final Project 

### ISSUE THREAD

**Issue by shuroq** [valencia-cop1000-201620/final-project#21]
### Name
Shuroq Talal

### Proposed Project Description
I'm thinking about doing a cashier machine in Python that works as a cashier. I think It will be easy to me because I love to work with numbers as we did in the calculator project.
The cashier machine would have the following features: 
* ask for the cost.
* ask for the tender. 
*will count the change exactly. 

### Connecting Concepts
My programme will cover chapter 3 - function. Also, this project will allow me to practice the concept of  manipulating strings as well as debugging

### Timing
I believe I can do this in one week, I am almost comfortable with all the features except  how to put all together in other words how to do the connection between the function. 
here's my proposed plan:

By next Wednesday, April 20
get final approval
have a design with descriptions of how the functions will all work
By next Friday, April 22
have a draft version of my code.
By Monday, April 26
have a finalized version of my code ready for feedback.
By Wednesday, April 27
finalize any changes to my code for final submission

### Asking for...
does anyone do something like that before?

**Comment by halfaro1** [comment]
@shuroq great idea, make sure you're creating an original program. There's a lot of calculator/cashier programs on the web and I'd ❤️ to see yours set apart. Before I approve this, I'd like to see some more detailed explanations of how your program would work. You mentioned that it will count change, how will it do this? Show some different options of cash tendered and change due.

**Comment by shuroq** [comment]
@halfaro1 Thank you for your feedback professor, My idea is to do a script came with two inputs. For instance, cost and payment . This script work to determine the change with the exact value, one dollars, 50 , 25,10,5 or 1 cent. Basically, my program works like a vending machine and how it's determine the change then return it for the customers.

**Comment by ngocnguyen83** [comment]
I like this project. It's simple but very useful. Let's make it more interesting. For example, a customer buys a bottle of water which costs $3.74. He or she puts in $5 bill. The change is $1.26. So the machine can dispense $1 bill, 1 quarter, and 1 penny. Or, just consider the odd part, 5 nickels + 1 penny, etc. Normally, the machine will be designed to choose the first option. How about there is no more quarter in the machine? The program needs to take into account his situation. Of course, it should  choose the option that results in least number of coins for customer's convenience.

**Comment by ngocnguyen83** [comment]
The program may receive an initial number of coins for each type. For example, 50 coins for quarters, 50 for dimes, etc. Test the program with different inputs until one (or many) type of coin is empty. Let's see how it moves from one option to another option.

**Comment by jmendez50** [comment]
Will you also need to input tax? Because that might be something more real world.

**Comment by halfaro1** [comment]
@shuroq thanks for keeping 👀 on this! 

Definitely think about the suggestions provided by @jmendez50 and @ngocnguyen83. Don't feel pressured to add complexity because ultimately it is your grade at stake. I think you could start with "version 1" exactly as you described, and in "version 2" add @jmendez50's tax idea and in "version 3" you could add @ngocnguyen83's limited coin idea.

Before I approve though, I'd still like you to flesh out how your program will run in detail. So please provide at least 5 examples of cash tendered and what the cashier would show in return.

**Comment by shuroq** [comment]
@halfaro1 great ideas I like it. as you said I'll do 3 versions. My original version will ask for the cost and cash tendered then it will give the exact change in twenties, tens, fives, ones, cents, quarters,dimes,nickels, and pennies. For example, if the cost is 30 and the cash tendered is 50 the change will be 20.00 ( two tens).
 Another example if the cost is 20.22 and cost tendered is 25 the change will be 2.78 ( 2 ones, 78 cents wich is 3 quarter and 3 pennies). 
if the cost is 250.99 and the cash tendered is 300 the change will be 49.009999( 2 twenties, 1 five, 4 ones, and one pennies).
if the cost is 2040 and the cash tendered is 2050 the change will be 10 ( one ten).   
if the cost is 15.77 and the cash tendered is 20 the change will be 4.23 ( 4 ones, 2 dimes, and 3 pennies). I hope that I make it clear now. thank you guys @ngocnguyen83 @jmendez50

**Comment by halfaro1** [comment]
Awesome, I'm comfortable approving this. Don't forget to create a design document before you start development.

**Comment by halfaro1** [comment]
@shuroq I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
