### ISSUE TITLE
JoshuaRi final project "Bank"

### ISSUE THREAD

**Issue by JoshuaRi** [valencia-cop1000-201620/final-project#25]
Joshua Ritmo

### Proposed Project Description
For my final project I would like to do something similar to how a bank works. I would have depositing into the bank. As well as loans where you will have to pay 105% of the loaned amount over the course of 10 months. You will manage your money as you wish. The menu would be asking how each command will work and what they do it will be asking how much money you wish to receive monthly, which goes along with interest. The goal would be to manage your money. After each command it will state your current funds.

### Connecting Concepts
Functions as well as debugging the numbers.

### Timing
I think i'll be able to finish this at the earliest on Wednesday the 27th, and the latest possible the following on the Friday the 29th.

Is there anything I should change as far as percentages go? For instance loans taking more then 105% of the loaned amount and decreasing or increasing interest.

**Comment by halfaro1** [comment]
@JoshuaRi thanks for posting! I'm a little confused about all the different options. It would help if you posted what the menu would look like for the user.

**Comment by Nate388** [comment]
Would this be more like a game where you have an income, a balance, and the computer takes out a certain random amount?

I like the concept so far and I can't wait to hear more!

**Comment by JoshuaRi** [comment]
I was thinking more of you set a amount you get over time and you just play around with your balance. But I could also have it where you lose a random amount of balance over time and you will try to keep your balance.

**Comment by halfaro1** [comment]
@JoshuaRi thanks for the update, but I'd still like to know more about how the program would work. Could you please provide a detailed description, a sample menu, and a sample user/computer interaction?

**Comment by JoshuaRi** [comment]
Description/User interaction/menu

Example of someone using program-

Program:Hello and welcome to The Bank. For instructions type !help .

User:!help

Program: This is The Bank, where you decide how much cash you want to begin with, a set income and a range of money you will lose monthly, the goal is to manage your money and not go broke. The amount you choose as your income is how much money you will receive monthly, the amount deducted each month is from the number you choose and below so if you were to pick "100" each month you will lose $1-100 dollars. Once the game starts you may type "!skip" to go ahead a month, allowing for you to receive your income as well as interest (+4% of money before deduction and income) how much you will lose that month. You may invest your money into things. For instance if you type "!invest" followed by '50" you will invest $50 when you invest, you will have a 50/50 chance to win doubling your money so you will receive $100 after putting in $50. If you lose you will lose the $50. You can also receive loans with !loan , but when each month passes your range of money deducted will increase by that amount for instance if you had it set to $100 for how much money you will lose max a week and get a loan for $200 the range monthly will permanently increase by $200 so now you will lose $1-300 per month instead of $1-100. To begin type the amount of money you wish to receive monthly and the program will tell you the rest. The program will print the total amount of money you have after each command. You may type !close at any time to close the game.



User:100

Program:Now type the range of money you wish to lose monthly.

User:50

Program:Now you may begin your total is 100.

User:!skip

Program:Your total is now 190 (+100 , +4% interest, -14 deduction)

User:!invest

Program:How much do you wish to invest?

User:150

Program:You have invested 150 and have lost your payment.

Program:40

User:!loan

Program:How much do you need?

User:20

Program:Your deduction number has been increased by 20!

Program:60

User:!skip

Program:Your total is now 92.4.(+100,+4%interest, 70 deduction)

User:!close

Program: Thanks for playing goodbye!

**Comment by halfaro1** [comment]
@JoshuaRi thanks great job 👍

**Comment by halfaro1** [comment]
@JoshuaRi I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
