### ISSUE TITLE
DanielCowman: Final Project Proposal

### ISSUE THREAD

**Issue by DanielCowman** [valencia-cop1000-201620/final-project#26]
### Name
Daniel Cowman

### Proposed Project Description
I would like to create a currency conversion tool, the user would input the currency for their country (USA, England, Australia) and the country for which the currency will be converted to, also the user will need to enter how much money will be converted. 

Once all the information has been entered the program will pull live data from a JSON API (fixer.io) and provide the user with the converted amount that would be received if the user did convert the money. 

### Connecting Concepts
The program will consist of arrays, fetching third-party data, and handling user input.   

### Timing
I will have this project finished within 48-72 hours of approval. 

### Asking for...
1. How should I gather the users country and country they wish to convert to? Codes or Names?
    E.G ( Codes = USD, AUD, GBP; Country Names = USA, England, Australia)

Please provide any suggestions.

Thank you!

**Comment by larawillson** [comment]
@DanielCowman This is a great idea! I think it is something that could be quite useful in many situations. As for whether you should use code or names, I think that really depends on the audience that you are writing the program for. Plain Jane Lara has no idea what all of the different codes throughout the world are, however, someone who is in banking is familiar with those. Who do you see using this program?

**Comment by chrispelaez** [comment]
Great idea I could see something similar being included in "A backpackers guide" to help travelers calculate their cost when traveling in different countries.

**Comment by halfaro1** [comment]
@DanielCowman cool idea! and useful :) I'd recommend using currency codes as it will create a standard and you won't have to worry about misspellings or anything like that. However, @larawillson has a valid point that not everyone knows country codes. However, that could be easily mitigated by your program if you either (a) give the user an option to see all country codes -- you would just print them to the screen, or (b) link the user to a web page with all the country codes. 

As far as the implementation goes, how are you feeling about APIs? We didn't do any projects with APIs although it was in the reading.

**Comment by DanielCowman** [comment]
@larawillson, @chrispelaez, @halfaro1 Thank you all for the feedback, based on the comments above I will go with the country codes and on startup the program will print out a table with the codes and the corresponding country 

@halfaro1 I'll be working with Python and APIs soon, so this will be good practice for when that time comes. 

I have worked with a couple API's (UPS, Twitter) in different languages, so I'm sure it won't take much to figure out how to do it in Python.

**Comment by halfaro1** [comment]
@DanielCowman awesome, in that case I'm comfortable approving this 👍

**Comment by smoussadeq** [comment]
Daniel
I think this sounds like a great idea. I found your program useful. Definitely, you should take your audience in consideration in order to find out whether to use codes or names. I am interested to see how this turns out. 
Good luck!

**Comment by halfaro1** [comment]
@DanielCowman I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
