### ISSUE TITLE
LaraWillson - Final Project Proposal

### ISSUE THREAD

**Issue by larawillson** [valencia-cop1000-201620/final-project#27]
### Name
What's your real name? Lara Willson

### Proposed Project Description
I've been inspired by all my classmates projects that seem to be reminiscent of childhood games. I want to create a python program that runs a Madlib. Madlibs are a way of creating a unique story by selecting words without knowing the context they will be used within the story. To make it a bit more difficult, I want to start off by having the user select the genre that they want their story to be (i.e. superheroes, spooky story, alien abduction, etc.). Once they choose from the genre options, the will be prompted for the words they want to use in their story. The program will then print the story in its entirety with the words selected by the user. After telling the story, the program will prompt user if they would like to do another Madlib. My goal is to have five different genres/stories.

### Connecting Concepts
What chapters/topics will this project allow you to practice? A good final project will cover at least 2 distinct topics from class.  This project will be done using the topics from chapters 1-4 of the textbook. It will definitely focus on the python basics. Variables are going to be hugely important, as will concatenation.

### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates. I should be able to have this project complete by it's due date April 27th :) My tentative schedule: 
April 22 --> Approval
April 25 --> 1st version up
April 27 --> Any updates completed

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?
I'm open to any and all feedback!

**Comment by Chummel** [comment]
This actually seems really interesting. Would you have the users pick their words from a list or simply input their own?

**Comment by larawillson** [comment]
@Chummel I was thinking that I would just prompt them with "enter a noun" and they can enter any noun they can think of. So simply inputting their own words

**Comment by halfaro1** [comment]
@larawillson love this idea! Let's spend this time that you have our attention to start coming up with your stories. Please post (you can edit your original post and comment when you're done) the genres or the stories with the placeholders for the user input.

**Comment by larawillson** [comment]
[MadlibsProject.docx](https://github.com/valencia-cop1000-201620/final-project/files/232664/MadlibsProject.docx)
@halfaro1 I have gone ahead and attached a file with the different stories and prompts for the program. Once the user goes through the first prompt and selects a story, they will then be prompted with the word type in astericks. In the end, I will take the users response and insert them into the final story that is printed back to them in the end.

**Comment by halfaro1** [comment]
@larawillson love it! Full team ahead 👍

**Comment by rtran4** [comment]
I hope your stories are great! Good luck! This seems like a fun project and I can't wait to test it when you're done!

**Comment by halfaro1** [comment]
@larawillson I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
