### ISSUE TITLE
JoetheJedi Final project proposal

### ISSUE THREAD

**Issue by JoetheJedi** [valencia-cop1000-201620/final-project#28]
### Name
Joseph Gonzalez

### Proposed Project Description
This is kind of similar to another classmates proposal. As a avid gamer I'm always looking to play new games but they have to be my style of game. I want my program to ask the user what genre of games they like the most and depending on their answer the program will open their browser to a youtube playlist ill create that contains trailers of games I think they might enjoy, based on their answer.

### Connecting Concepts
Two chapters ill definitely be using for this project is chapter 3 flow control and the web-scaping chapter.

### Timing
4-23: I hope to have at least 4 genre playlists created and ready to implement into the code
4-25:Should have a near completed draft uploaded and use any feedback received to better/simplify the code.
4-27:Final project uploaded 
### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?
If you see anyway my code can be simplified that would be useful or any insight at all will be useful.

**Comment by EvanLuke** [comment]
This is a pretty interesting concept. Perhaps it could also link to a website such as IGN's top games for the year for each genre.

**Comment by halfaro1** [comment]
@JoetheJedi cool idea 🎮 . Since the playlists don't require any code, I'd like to see those posted here before you implement. Will the user pick their favorite genre from a list? Or will they have to type in genres? If they have to type it in, how are you going to deal with misspellings or something you didn't expect? Since your project is pretty straightforward (that's not bad), I'd recommend adding one more thing of value like @EvanLuke suggested.

**Comment by elicegreen** [comment]
I really like this idea. Perhaps give the user an option to either 'search' for a game (allowing the user to type the name of the game) or to 'browse' for games (allowing the user to pick from a list of genres, and then a list of games.

**Comment by halfaro1** [comment]
@JoetheJedi how are you doing on incorporating our feedback? I'd like to approve this so you can move forward as soon as possible.

**Comment by JoetheJedi** [comment]
@halfaro1 I'm thinking of changing up the original idea. How about firstly asking the user what genre they like the most, from there the program sends them a list of games from that genre that I personally like with a brief description of said games. Then the user chooses one of those games and the program opens a trailer of the chosen game on youtube

**Comment by JoetheJedi** [comment]
to be clear the user will pick from a list of genres I provide

**Comment by mviruet2** [comment]
@JoetheJedi I like of the program opening a trailer of the chosen game.

**Comment by JoetheJedi** [comment]
@halfaro1 I took your feed back and to deal with misspellings i added when True statements to make sure they dont mess up the program. Also instead of just having it choose a genre then open a bunch of games I listed the games individually after choosing the genre to make it less simple

**Comment by halfaro1** [comment]
@JoetheJedi I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
