### ISSUE TITLE
SaidMoussadeq's final project Proposal

### ISSUE THREAD

**Issue by smoussadeq** [valencia-cop1000-201620/final-project#29]
<img width="640" alt="runningexample" src="https://cloud.githubusercontent.com/assets/16658951/14845049/c4321540-0c29-11e6-9a27-9e39d2b4dcaf.png">

My program is a tip calculator. It counts the percentage and therefore the total of the bill. 
The program will ask you : 

-How much is the total of your meal?

-How was the service?

-what percentage would you like to tip?

-Lastly, It will calculate the total of your whole bill.

P.S above is a picture of how the program look like.

# Name

Said Moussadeq

# Proposed Project Description

Since I work in the Restaurant industry as a waiter, I decided to came up with a project that calculate Tips average. The program will have the following:

- Ask the user how was the service.

- If the service was okay, the tips will be 15%

- If the service was good, the tips will be 18%

- If the service was excellent, the tips will be 20%

- Then the program will calculate the total of the bill

# Connecting Concepts

I will be definitely using the following chapters from the textbook : Python Basics, Flow control and Functions. 

# Timing

Wed 22th Apr 2016 : I should receive approval
Wed 25th Apr 2016 : I should have my draft in order to utilize professor's and student's feedback 
Wed 27th Apr 2016 : Have my project uploaded

# Asking for...

Any ideas that can be added to my project?
Since I didn't submit my proposal as earlier as I should, do you think I will have enough time ?

**Comment by EvanLuke** [comment]
This is a very good idea, maybe you could add best 2 out of 3 to make it a little harder and a bit of a longer game for the user.

**Comment by chrispelaez** [comment]
I am doing something similar getting the program to loop was a doozie but after figuring it out I'm trying to add other options other than rock paper scissors. If you hit a road block don't hesitate to ask for help.

**Comment by halfaro1** [comment]
@smoussadeq since @chrispelaez is doing something similar (see Issue #19), I'd think about how you could either (a) change the current idea so it adds something unique or (b) try a different game/project. If you need help coming up with idea, I'm sure these awesome classmates can give you some 😉

**Comment by nhatnam113** [comment]
Smart idea and great game bro!

**Comment by smoussadeq** [comment]
@halfaro1 I updated my project.
Will you please take a look at it ?

**Comment by halfaro1** [comment]
@smoussadeq I like this idea much better! Please makes sure your design document contains some sample total bills and different possibilities for the tip/rating and calculation. Approved 👍

**Comment by smoussadeq** [comment]
Thank you so much! Definitely I will give it my best professor @halfaro1

**Comment by halfaro1** [comment]
@smoussadeq I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
