### ISSUE TITLE
Xyngabo: Final Project Proposal

### ISSUE THREAD

**Issue by xyngabo** [valencia-cop1000-201620/final-project#3]
Alex Cassell  :crystal_ball: :computer:

### Proposed Project Description
The Python program will open a simple random number javagame @ http://alexcassell.com/javagame
The program will choose a  Number to start
Based on feedback (high or Low)
makes a second guess 
(1/2(n+1) I should be able to make the program always guess it in 7 turns or less.
**It might look something like this:**

### Initial
![Image of initial](https://www.alexcassell.com/assignments/project/initial.png)

### When guessing:
![Image of initial](https://www.alexcassell.com/assignments/project/guessing.png)

### When wrong:
![Image of initial](https://www.alexcassell.com/assignments/project/wrong.png)

### If the program never guesses correctly (10 tries):
![Image of initial](https://www.alexcassell.com/assignments/project/nope.png)
then exit

### Connecting Concepts
The program will at the very least span both: Chapter 11 - WebScraping and Chapter 2 - Loops.

### Timing
The project will probably take several hours (I still need to change my java game to give outputs that are easily read by python)

### Asking for...
Does this fit the scope of the assignment?

**Comment by ryby6969** [comment]
I played your Java version and it was pretty cool. Are you going to make it strictly code based or will there be an interface like the one in Java?

**Comment by halfaro1** [comment]
Good start, @xyngabo but yeah I want to know the same thing as @ryby6969

**Comment by xyngabo** [comment]
The program will go to my website and it will play the javagame.  No interface, the program, just guess and then check to see if it is correct and then do more guessing.

**Comment by halfaro1** [comment]
@xyngabo thanks for the clarification -- and I played your game a little more thoroughly, how fun! I loved the wizard 🔮 . Since you have no interface, could you add an interface so the person running your program could see what's happening? It would also help if you post what the user would see as a response from your program when running.

**Comment by xyngabo** [comment]
@halfaro1 Ok I have posted some screenshots

**Comment by Lamle104** [comment]
Pretty cool program. Visited your website and played the game. Like the idea.

**Comment by shuroq** [comment]
great program!!! For sure I would like to try it after you finish it. Good luck in your final project

**Comment by elisenharper** [comment]
I like the interface you set up in Java. I hope to learn how to do that soon! Also liked the sound effects that went with it. Good luck on the final project!

**Comment by halfaro1** [comment]
@xyngabo I like it! Great work, you have the 👍 to start implementing.
