### ISSUE TITLE
Chummel's final project proposal

### ISSUE THREAD

**Issue by Chummel** [valencia-cop1000-201620/final-project#30]
### Name
Colin Hummel

### Proposed Project Description
I was thinking of creating a sort of career test. It would start off with broad questions and as the test would go on they would become more specific. All of these questions would be personality questions asking the user to submit input. After a certain amount of questions you would be given a career best suited to your questions answers. There would be probably around 10 career possibilities. 

### Connecting Concepts
It would cover not just the basics of python coding but it would also cover, user input, path flow, variables, and it would assign certain careers attributes as well.
### Timing
4/20/2016: Hopefully I am approved.
4/21/2016: I'd begin my coding.
4/24/2016: If I've had enough time I'll submit a rough draft
4/27/2016: Taking student input and potential changes into consideration I'll revise, finalize, and submit my final.

### Asking for...
Any ideas? Anything at all. Career possibilities? Flare options?

**Comment by EvanLuke** [comment]
The input for the user would have to be a simple question, or a multiple choice. But true or false would be easiest. I think it would be incredibly hard to do it any other way. However if they were simple questions with true or false answers it would be easier.

**Comment by halfaro1** [comment]
Great feedback @EvanLuke -- true or false would be way easier.

@Chummel I'd suggest spending some time while we are going through approval to look up career surveys and use something that's already been created. No sense reinventing the wheel! Please post those surveys that you find in this issue.

**Comment by Chummel** [comment]
@EvanLuke good idea, I think I am going to go with true or false. And @halfaro1 , yeah I had plans to look at some other career surveys to see what they thought would be certain characteristics for certain jobs.

**Comment by MarcialSegura** [comment]
I had a very similar idea for my final project and I was thinking the same thing and keep it True and False so it will be less complicated.

**Comment by jashhhhhhh** [comment]
Programs like this have a wide use. I agree with Marcial's above comment as well; keeping the response options to a minimum will help you reduce the amount of coding. Could assign a point to each true answer and then assign the range of totals to reference the careers? Maybe this could work as a simple math equation?

**Comment by gkaja14** [comment]
Good idea, you also can get some ideas form my education plan under lifemap tap in your atlas account.

**Comment by halfaro1** [comment]
Glad to see the discussion that's taking place here!

@Chummel I'll be ready to approve this as soon as you post some potential career questions.

**Comment by halfaro1** [comment]
@Chummel how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by Chummel** [comment]
@halfaro1 I'm doing fine actually. Sorry I had to drive down to Florida from New York and it took some time. And the questions wouldn't really get too specific until maybe one to two in. As for the first ones, I wanted to start off with determining whether or not it'd be a creative career or say a "black and white" type of career by asking "Do you enjoy mathematics?" and then from there it'd break into two different subsets on questions, one based on the creative jobs, one based on more scientific and math related jobs.

**Comment by halfaro1** [comment]
@Chummel ideally you'd come up with all the questions before you begin development. Do you already have all the questions you're going to be using? Can you post them here? When you do that I'll mark this as approved.

**Comment by Chummel** [comment]
[Doc1.docx](https://github.com/valencia-cop1000-201620/final-project/files/237524/Doc1.docx)
@halfaro1 I created a little hierarchy chart to show the questions and results, the "(Y)" next to something means that the answer to the question was yes and the "(N)" means the response was a no. It's not entirely specific but it's just a generalization of where people could work.

**Comment by halfaro1** [comment]
@Chummel thanks, where did you get these from?

**Comment by Chummel** [comment]
@halfaro1 I just assumed careers based off of general questions. Right off the bat I wanted to separate the careers into more creative and then more statistical careers.

**Comment by halfaro1** [comment]
@Chummel aright for the purposes of programming this is find. But if you want to create something useful (and who doesn't), I recommend you base your content on something real like research. In terms of careers there are plenty of career assessments widely available. Start with a version 1 of your code with the questions you have already. Maybe for version 2 of your code, you should expand the questions and utilize some other career assessment. Make sure the assessment you use is either open source or that you have permission from the content owner to use it. In both cases, you should give credit to the content owner.

**Comment by halfaro1** [comment]
@Chummel I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
