### ISSUE TITLE
Evan Luke Final Project Proposal

### ISSUE THREAD

**Issue by EvanLuke** [valencia-cop1000-201620/final-project#31]
Evan Luke 

Hangman Game 
I would like to create a game of hangman. Or something very similar, where the program chooses a random word from a list. Then the user is prompted to guess a letter, and would only have a certain amount of attempts. The program would have to make sure the user enters only one letter at a time and then check if it is in the word. 

This project would cover a few concepts from the course. It would use strings, if/elif functions, lists, etc. 

I think I can finish it in a week. I have already jotted down an idea of how it would look. 

I am just curious if it would be to hard for only one week.

**Comment by chrispelaez** [comment]
sounds good cant wait to play!

**Comment by halfaro1** [comment]
@EvanLuke I don't think it's too hard, it sounds just right to me. I would like to see what you jotted down (that's part of this design and brainstorming process 😄 ). Could you also please post a simulated gameplay between the user and computer?

**Comment by EvanLuke** [comment]
@halfaro1  
Basically the code would use the random.choice function from a list of about 20 words. It would then take the users input, which would have the parameter of being one lowercase letter and would check if the chosen word contained it. Once the user has reached the maximum amount of attempts it will say hangman and show the word. Unless the user gets the word, in which case user will have won and the word will appear. 

Example:

'Welcome to hangman. A word will be chosen at random and you will input a letter to try and guess the word. You have 10 attempts. '
'Guess a letter'
F
'Please enter a single lowercase letter'
f 
'The word does contain ''f'', you have 9 attempts left. Guess a letter. '
g
'The word does not contain ''g'', you have 8 attempts left. Guess a letter. '
(Etc...)
'The word does contain ''l'', you have guessed the word ''fool''. Congratulations, you have won!'

**Comment by halfaro1** [comment]
@EvanLuke awesome. I'm leaving this open for another day or so to allow other folks an opportunity to give you feedback, but please start Part 2 of the project by filling in your design document and then you can begin implementing. But consider this approved 👍

**Comment by ukates** [comment]
maybe it would be complicated but i don't know, maybe you could have it print out a design of the hangman character after ever guess, like when you do it in your notebook! I remember one of our projects had us printing the game board for tic tac toe, maybe you could find a character type design online for a hangman board that python could print. +---+
  |   |
      |
      |
      |
      |
=========

  +---+
  |   |
  0   |
  |   |
      |
      |
=========

  +---+
  |   |
  0   |
 /|   |
      |
      |
=========

  +---+
  |   |
  0   |
 /|\  |
      |
      |
=========

  +---+
  |   |
  0   |
 /|\  |
 /    |
      |
=========

  +---+
  |   |
  0   |
 /|\  |
 / \  |
      |
=========

**Comment by ukates** [comment]
The hangman board looked a lot better on google images, but you get the idea. @EvanLuke

**Comment by EvanLuke** [comment]
@halfaro1 Thank you!

**Comment by halfaro1** [comment]
@EvanLuke three back quotes (`) (accessible via shift and tilde ~) allows you format text like code, so it allows you to do cool things like this:
```
 +---+
 |   |
 0   |
/|\  |
/ \  |
-----+
```

**Comment by halfaro1** [comment]
@EvanLuke I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
