### ISSUE TITLE
jashhhhhhh's Final Project Proposal

### ISSUE THREAD

**Issue by jashhhhhhh** [valencia-cop1000-201620/final-project#32]
### Name
Joshua McKnight

### Proposed Project Description
I work for a nonprofit that is dedicated to open-sourcing the worlds best solutions for sustainable abundance. Humans Unifying Global Solutions is still early in its development and requires more reach and funding. I am proposing to design and create a program that will ask users for their email and then store this email into a file. I could also ask what specific area or types of content they are interested in and sort the emails into groups based on the user's selections. This type of data collection can be very useful in expanding our reach as an organization. Monthly newsletters, Calls to Action, project updates and other documents like this can be easily and quickly shared to a wide audience by email list.

### Connecting Concepts
This project will pull concepts from several chapters in the textbook. It will use functions from chapter 3 to collect and send the data. It will use file opening/writing from chapter 8 to save the data. Also, it could possibly work with pdf/word documents from chapter 13 to create an easy to read document.

### Timing
This project should take no longer than 1 week to complete.

### Asking for...
Any and all feedback/suggestions is welcome and appreciated!

**Comment by halfaro1** [comment]
Thanks for the proposal, @jashhhhhhh 

Will this program run on the command line? Or are you somehow going to integrate it into a web page?

**Comment by jondisla** [comment]
I like it too.  If you can get it on a web page that would be very impressive but on the command line is fine too which is what I would do.

**Comment by halfaro1** [comment]
@jashhhhhhh how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by jashhhhhhh** [comment]
For the purpose of the class final I am just using the command line. However I may attempt to incorporate it into our website in the future. Thanks for understanding my late response, I was away from home this weekend!

**Comment by halfaro1** [comment]
@jashhhhhhh ok 👍

**Comment by halfaro1** [comment]
@jashhhhhhh I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
