### ISSUE TITLE
Nicholas Ivey Final Project Proposal

### ISSUE THREAD

**Issue by nickivey2** [valencia-cop1000-201620/final-project#34]
### Name
Nicholas Ivey
### Proposed Project Description
I am going to port my Jarvis Personal Assistant I created in C# prior to this class to Python.
https://github.com/nickivey/Jarvis
Old Video: https://www.youtube.com/watch?v=6Fyzdf_DOE0
Porting Jarvis to Python will allow me to run Jarvis on my Raspberry Pi instead of a Windows Machine. Using Google Voice Recognition, Jarvis will tell you the day of the week, time, and the weather.  Also Jarvis will be able to perform google searches and control system volume. 
### Connecting Concepts
What chapters/topics will this project allow you to practice? A good final project will cover at least 2 distinct topics from class.
Jarvis will contain user input from voice and text and will return corresponding responses.
Parsing a HTTP JSON request Jarvis will be able to read the user weather information.
### Timing
4/20/2016: Approval
4/21/2016: Begin Development
4/24/2016: Layout of application
4/26/2016: Finalizing features
4/27/2016: Submit Application

### Asking for...
Any ideas or suggestions.

**Comment by halfaro1** [comment]
@nickivey2 if you're comfortable with this, I'm comfortable with it. Could we get a little bit of information about the structure of Jarvis as it currently exists in C#? Something high level that other students can benefit from would be ✨ 

I'm leaving this issue open for a day or so to allow other students the opportunity to give feedback and check it out :)

**Comment by Nate388** [comment]
This is amazing! I've always wanted to do something like this when I got more experience.

**Comment by halfaro1** [comment]
@nickivey2 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
