### ISSUE TITLE
Nam Nguyen Final Project

### ISSUE THREAD

**Issue by nhatnam113** [valencia-cop1000-201620/final-project#35]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
Nam Nguyen
### Proposed Project Description
Have you ever thought about have a cat? Have you ever thought that cat is the good pet for you?  I love animals, especially cat. In my final project, I will write a program that let you get your best cat.  If you are looking for a lovely cat, my program may help you. I know it is very hard to looking for a cat. I hope my little program will help. 
About the program, I will give you some questions and the user have to answer all of them. In the end, the program depends on your answer and say "you are good to adopt a cat" or " sorry, you are not ready to adopt a cat."
### Connecting Concepts
It will cover from chap 1,2
### Timing
It will take me 2 or 3 days to finish
### Asking for...

Please give me some good feedback to make my program better. :)

**Comment by halfaro1** [comment]
@nhatnam113 thanks of the proposal! I'd like to know more about how your program will tell you about cats. What's the interaction going to be between user and program? What will the program be using for its source of truth?

**Comment by Nate388** [comment]
I'd love to know more about how your program will help me find a lovely cat!

**Comment by jmendez50** [comment]
Well if it has a lot of cute cat pics then I'm sure its worth of an A. lol

**Comment by gkaja14** [comment]
Sounds like a cool program, and it will help us to know more about the cats!

**Comment by JoetheJedi** [comment]
I love cats as well haha. Are you going to make a list of cats and have the user choose one/multiple?

**Comment by halfaro1** [comment]
@nhatnam113 how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by nhatnam113** [comment]
Hi Professor,
Thank you for asking. I'm working on this and I should update all the missing information by tonight.
________________________________

**Comment by nhatnam113** [comment]
@halfaro1 for my final, the interaction between the program and the user is I give them two options about cat's sizes. This is a little bit look like a form. You pass all step and you get your best cat.

**Comment by nickivey2** [comment]
Ive been looking for a pet cat. Love the idea cant wait to see it happen!

**Comment by nhatnam113** [comment]
@nickivey2 thank you very much :) :)

**Comment by halfaro1** [comment]
@nhatnam113 let's flesh out the list of questions. What questions would be asked by the program. What does the program do with each possible answer?

**Comment by nhatnam113** [comment]
@halfaro1 
1. Do you love cat?
2. Do you looking for a lovely cat?
3. what size of cat are you looking for?
4. Do you know how to take care of a cat?
These 4 questions will be asked in the program. The program will give the user the best choice depend on the user's answers.

**Comment by nhatnam113** [comment]
@halfaro1 
Do you like cat?
Do you looking for a cat?
What sizes are you looking for?
Do you know how to take care of a cat?
Do you know how to train a cat?
Do you know how to play with cat?
Do you let jump into your bed?
Do you enough age to own a cat?
Do you take your cat to anywhere with you?

After the user answers all those questions, the result will be based on their answers and give them a lovely cat

**Comment by halfaro1** [comment]
@nhatnam113 what are the results though?

**Comment by nhatnam113** [comment]
@halfaro1 I mean like after the user answers those questions. The program will tell " Congratulation, you are good to have a cat" or " Sorry, cat is not a good choice for you."

**Comment by halfaro1** [comment]
@nhatnam113 oh! I misunderstood. I thought your program was going to let you select from multiple breeds of cats or maybe colors of cats or something. Well, the program as you described it is pretty simple, but could be done as long as (a) you use more than 2 functions to achieve what you want to do, and (b) you add something that makes it a little more complex so it covers more than just one chapter in the book

**Comment by halfaro1** [comment]
@nhatnam113 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
