### ISSUE TITLE
LuisDavilaBermudez's Final Project Proposal

### ISSUE THREAD

**Issue by LuisDavilaBermudez** [valencia-cop1000-201620/final-project#36]
Luis Davila-Bermudez

**Proposed Project Idea**
I'd like to create a program that will allow you to change images. A program where you tell it to make the image a thumbnail size or to change the color of the image to red. The program will ask you to tell it what to do with the images that are in the folder that the program receives images from. So the program will affect all images in the folder. So let's say someone needs a picture to be colored green then made a thumbnail size or the size of their choosing, as well as have a logo on it. You can also do it in multiple languages.

**Topics Covered**
This project will use the first and last topics of the class.

**Timeline/Time it Takes**
First, I would set up the logo addiction part.
I would then have to implement the Spanish version which wouldn't take too long since i'm just rewriting the original code. I'd say I could do that part in about a few hours.
I would be able to finish this over the weekend.

**Feedback I Would Like**
What could I add to the program, like any other features which will take the program to a new depth.

This will be near and dear to me since I could easily do this in Photoshop, which I have had years of practice with. So this will be a more challenging way of doing something simple.

**Comment by halfaro1** [comment]
@LuisDavilaBermudez great idea! I have a few suggestions. First, narrow this down to a program that does one task (like making thumbnails). If you finish early and can add functionality, it's icing on the 🍰 and won't cost you points. My second suggestion is that if you decide to do things like recoloring, I'd ask you to explain what that means. Maybe post an example? Third, I wasn't sure what you meant about languages -- do you mean that you'd like to create a program that can be executed in different spoken languages?

**Comment by LuisDavilaBermudez** [comment]
What I meant is that the program opens and then asks you for a language. The program then asks what you want to do with it like making it a thumbnail size or adding in a logo in your chosen language.

**Comment by halfaro1** [comment]
@LuisDavilaBermudez I see! Well I would consider the language thing one feature. So my suggestion is: start with "version 1" in English with 1 functionality (whatever your favorite functionality is, I used "create a thumbnail" as an example). Consider that your submission for credit. Then, you can work on "version 2" which could have a Spanish option in addition to English. "Version 3" could have an added functionality, like add a logo to an image, and so on. If you'd like to move forward with my suggestions (or your own or classmates'), edit your original post with the modified idea and detailed explanation.

**Comment by halfaro1** [comment]
@LuisDavilaBermudez how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by LuisDavilaBermudez** [comment]
I have finished 3 different programs that run to change the original images.

The only thing left would be to put it in Spanish.

________________________________

**Comment by LuisDavilaBermudez** [comment]
I just saw my mistakes on the manipulating images project and I saw that it hasn't been graded yet so I was wondering if there was a way to resubmit it.

________________________________

**Comment by halfaro1** [comment]
@LuisDavilaBermudez you never did tell me how you were moving forward, so did you decide to implement the changes we discussed and that I suggested? If so, I can move this to approved, if not we need to talk about it more. Do you have an open pull request also?

**Comment by halfaro1** [comment]
@LuisDavilaBermudez also the issue with Pillow is one that needs to be corrected -- it's not possible to write a program without being able to test it. Have you reached out to resolve that issue one on one?

**Comment by LuisDavilaBermudez** [comment]
I did use your suggestion, and if I can call you I would like to know when I could.

**Comment by halfaro1** [comment]
@LuisDavilaBermudez alright I'll look at the open pull request. Can you link it here please?

**Comment by LuisDavilaBermudez** [comment]
https://github.com/valencia-cop1000-201620/final-project/compare/master...LuisDavilaBermudez:master

**Comment by halfaro1** [comment]
@LuisDavilaBermudez :point_up_2: I gave some feedback on the pull request directly

**Comment by halfaro1** [comment]
@LuisDavilaBermudez I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
