### ISSUE TITLE
Nate388's final project proposal

### ISSUE THREAD

**Issue by Nate388** [valencia-cop1000-201620/final-project#37]
Nathan Spencer

I was thinking maybe like a text adventure similar to the style Dragon's lair (if you have never played dragon's lair https://www.youtube.com/watch?v=P3XNQja0H7I). You have various choices to choose from until you get to the end of the adventure. You'll have various endings depending on what you chose (mostly death) but the true ending will take place with all the right choices. I'll include lots of narrative to keep things interesting and maybe include small details into it to hint at the choices. and at the end maybe do a slightly more interactive boss?  

Most of the heavy work would be flow control. So much flow control. But string manipulation will also be big task to handle.  

I'll be honest I'm already behind a little as it is. That being said I think I can do this fairly quickly within a couple days work depending if I actually do something for the end.

what do you think, Should I pursue this kind of program? I was also thinking of a more traditional text adventure, which would be a little bit easier. But regardless I'd have fun making both of these.

**Comment by halfaro1** [comment]
Great idea, @Nate388. I'd be careful not to step on the toes of @BobbyGatlin (see Issue #12). My suggestion would be to make the game completely different. Before this is approved, I'd also like to see you think through what the game would look like. What's the story? What does the map look like? What characters would the player encounter (if any)? What results in death? What's winning?

**Comment by Nate388** [comment]
Ok, so so unlike **@BobbyGatlin**'s idea, which is awesome by the way, the gameplay for my game would be more or less trail and error. the player will be presented with 2-3 choices, 1-2 bad and one good. choosing a bad choice will result in death and the player would start from the beginning, and a good choice will result in the player moving on to the next series of choices. Their would be a short description of each new encounter, such as scenery, objects, people, etc. I would try and make these descriptions hint at the good choice in the scenario while not totally giving it away. I like sci-fi so let's say the story takes place with the player being stranded in an unknown populated city and he has to reach some space pirates who took his ship and stranded him in the first place. The winning condition is making it to the end and successfully getting your ship back (can't spoil the ending after all)

**Comment by ngocnguyen83** [comment]
I haven't played video game, but your idea sounds interesting to me. I think it will involve many loops, so you may need to do it carefully.

**Comment by Nate388** [comment]
Right I was thinking about that a while ago but I think I could work it out. the code would look something like this
     
`while True:
    print("you find yourself in a dark place. Stranded by those blasted pirates.")
    print("will you go to the city or to the jungle?")
    user = input()
    if user == "jungle":
        print("you get eaten. GAME OVER")
    if user == "city":
        print ("you go to the city")
        break`

And so on until the end. fairly straightforward so if I can really flesh it out I can add extra dialogue, options, and maybe add in that boss fight!   

Thank you. You made me think about my code more before I executed it!

**Comment by digitalBeast** [comment]
That going to be fun to play, I love games and I wana make my own and little by little I wana make more interesting games. As far I can tell, try not to over stress yourself in making a long program. Remember! The game is at the best with the best story, not the best graphic. You got this!

**Comment by halfaro1** [comment]
@Nate388 I love your pseudocode -- it's a great way to begin to think about the game logic. And I'm confident it'll be original 😄 

I'm almost ready to approve, I just need to see you plan out the different options for the player (before you program). Once you post that, we'll be ready for the 👍

**Comment by Nate388** [comment]
I'm not sure what you mean. In my post above I demonstrate how two options are presented to the player. More narrative will be included, is that what you're looking to see?

**Comment by halfaro1** [comment]
@Nate388 I'd like to start seeing some of the narrative now, or at the very least an outline of the storyline.

**Comment by Nate388** [comment]
@halfaro1 Ok. So my idea is to convey the 'correct' choice to the player through the narrative. Here is a rough draft for the first dialogue when you start the game and the first choice is presented.

"The sound of the fierce wind wakes you up from your disgruntled state. You try and remember, "what was it you were doing?" It's so hard to think with this throbbing pain in your head... Wait. The pain. Those men. They said they were after something of yours. But what was it? It's so hard to think but you remember that it's important. You remember they jumped you, took you to the outskirts of the CITY, and hoped to leave you for dead. You can see the CITY from here, it's not too far to WALK. But there's a huge strange cloud rolling over the horizon. And it's fast. You think maybe it'd be better to RUN to the CITY. The wind picks up. You need to make a choice."

"Do you RUN to the CITY or WALK to the CITY?"

The key to this choice is the beginning. The wind that wakes you is fierce, but also at the end the clouds aren't just rolling above, but over the horizon and fast. 

If WALK is selected: "You start walking towards the CITY. The wind constantly at your back. The wind picks up. stronger. STRONGER. After some time walking the wind finally concerns you enough for you to look behind. "SANDSTORM", you yell as a wall of sand, rock, and gravel hit your human form.

"A couple hours later a search and rescue drone is scanning the desert dunes for survivors. "no life signs detected." it chimes as it heads back towards the city."
"GAME OVER"

If RUN is selected: Something doesn't seem right. You remember this kind of cloud from before, not just here but other places too. You dart in a full sprint towards the CITY. The wind is picking up, you don't have much time. You can hear alarms from the CITY shouting at full blast, "SANDSTORM APPROACHING, PLEASE STAY INDOORS." You make it to the CITY on time and head into the nearest open door, which closes fast behind you. You take a big sigh as you can already hear the effects of the sandstorm through the door. You're safe, for now.

In traditional text rpg fashion key items, places, and choices are uppercase so the player isn't left guessing what to choose from.    

The Story is that you're a man whose had something valuable taken from you. Your memory is rough but you piece things together along the way through different trials. The entire story takes place in the city so It won't be long enough to go anywhere else. The setting is futuristic but only a bit more advanced than we are today.

**Comment by halfaro1** [comment]
@Nate388 thanks! approved 👍 
It might also help to create a diagram showing the map or some visual representation of the gameplay. This would be part of your design document and doesn't have to be shown to the user, but I'd imagine it's an important part of programming a good, usable game.

**Comment by halfaro1** [comment]
@Nate388 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
