### ISSUE TITLE
jondisla's Final project proposal.

### ISSUE THREAD

**Issue by jondisla** [valencia-cop1000-201620/final-project#38]
### Name
Jonathan Disla

### Proposed Project Description
I am planning on making a Q/A game used for people to get to know each other or themselves.  My wife and I did a plenty of these games before getting married and I thought it would be fun to do this now that I can actually make one.  I'm still thinking if I should implement the random module in order to ask questions based on the answers given.  So I am planning on creating this game with the use of loops and random()

### Connecting Concepts
I will be using chapters 1-3 and chapter 6 in my project.  I will be using functions and manipulating strings.

### Timing
I don't have much time so I am hoping by the deadline.

### Asking for...
What do you guys think of this idea? I know it's a bit annoying a bunch of personal questions but I just thought it would be nice to get to know yourself or another person a little more.

**Comment by ngocnguyen83** [comment]
It's interesting Jonathan. I will play it, but could you please explain more about how the program works?

**Comment by jondisla** [comment]
The interaction would be somewhat as follows...

What is your name?

Jon

Welcome Jon! Press enter to begin.

INSTRUCTIONS: This program will ask you several questions about yourself.  After answering the true or false questions, you will hopefully have learned more about yourself and you can easily copy and paste the test and send it to some friends to see how they compare.

1. You love to meet  new people.
T/F
2.You are not afraid of talking in front of an audience.
T/F
3. You have a huge social circle.
T/F
4. You would rather spend time with one close friend than a bunch of people.
T/F
.....etc ( Still working on the questions there may be some not true or false.)

**Comment by jmendez50** [comment]
Trying to find love for your classmates. I like it lol.

**Comment by halfaro1** [comment]
@jondisla good idea! Might I suggest creating a "compatibility" score somehow? That way two players could get some value unique to your game. You could be on to something if you create a really good one, it's a competitive market ([example](http://www.nytimes.com/2008/01/29/science/29tier.html?_r=0))! I'll leave the implementation up to you, but one suggestion would be to have a score for 4 or so general areas that the player can compare against another player for compatibility. You can use some tests on the internet or (what I think would be more fun) is to create your own.

**Comment by ukates** [comment]
You could have the program run in two ways, you could have it run for just the one user and give a score or value back based on the answers provided.  The second way you could run the program is to make it for two different users, the program could say, "user 1 please answer the following" the user answers all the questions and the program stores that users value.  Then the program can start again saying user 2 please answer the following or something like that.  After user two has completed the questions the computer takes user number 2's value and compares it to user 1.  You can have the program say well if the score for user 1 and user 2 are within 2 or 3 points of each other  then the program can return that they are comparable! if they are not it could return "keep looking for another fish in the sea" haha i don't know but this can be made really cool

**Comment by aeuteneuer** [comment]
Jonathan,
I think this sounds like a great idea. I actually have never done a survey or played a game quite like this one.  I am interested to see how this turns out.  Might I suggest that at the end of the survey the user receives some sort of feedback depending on what was selected (if that already isnt planned on being implemented)

**Comment by halfaro1** [comment]
@jondisla how are you doing with incorporating our suggestions? I'd like to approve this so you can move forward as you only have a few days.

**Comment by jondisla** [comment]
Hey guys thanks so much for the suggestions.  I think they are great ideas!!! I would love to get a good match program perhaps with some collaboration.  As for the timeline for the project, I have been able to make some of the questions (not all) I intended to ask and also working on a way to combine the answers into a list but that's a work in progress....

**Comment by halfaro1** [comment]
@jondisla can you list the questions you used here? not the code, but a readable version of the questions and how they resolve to an outcome

**Comment by jondisla** [comment]
1.    At a party do you: 
a. Interact with many, including strangers 
b. Interact with a few, known to you 
2.    Are    you    more:    
a. Realistic than speculative 
b. Speculative than realistic 
3.    Is it worse to: 
a. Have your “head in the clouds” 
b. Be “in a rut” 
4.    Are you more impressed by: 
a. Principles 
b. Emotions 
5.    Are more drawn toward the: 
a. Convincing 
b. Touching 
6.    Do you prefer to work: 
a. To deadlines 
b. Just “whenever” 
7.    Do you tend to choose: 
a. Rather carefully 
b. Somewhat impulsively 

These are some of the questions.  The user gets to select either A or B.  At the end, I'm working on a list that will print out all the answers.  I was thinking this would be more of an online game so just one player for now but user 1 can actually send this list to a friend.  I submitted some code already in a pull request although I need approval first.

**Comment by halfaro1** [comment]
@jondisla I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break ☀️
