### ISSUE TITLE
Constructor's tool

### ISSUE THREAD

**Issue by ngocnguyen83** [valencia-cop1000-201620/final-project#39]
Project Name: Constructor's tool. 

Ngoc Nguyen 

In this project, I'm going to create a program that can do the following. 
- Receive tile's size  (which is square). 
- Receive room size : length and width (rectangular or square)
- Receive tile gap. 

It then outputs the number of full tile (and or partial titles) needed with the following rules:
- Titles will be divided, if necessary, so that opposite sides have equal space. 

For example, let's consider just one side, the length of the room. The length is 10 inches, the tile size is 3, and the gap is 0.05. 
Then we need 3 full tiles and 2 reduced size tiles (rectangular shape) which have one size of 0.4 inches. 

Sample Calculation:
The excessive space after 3 full tiles are applied: 10 - (3*3) - 0.05 * 2 = 0.9 inches. 
The excessive space after we applied two more gaps:   0.9 - 0.05 * 2 = 0.8 inches. 
This means that we need 2 reduced tiles with one size of 0.8 / 2 = 0.4 inches. Their other size will be 3. 

So, we put 3 full tiles in between of  two 0.4 x 3 tiles (In this case, only one size is reduced).
However, we have to consider the case where we need tiles whose both sizes are reduced.   
 
* Connecting Concepts
Input, output, and loop. 

* Timing
I think this problem will take me 3 days to finish. 

* Asking for...
ideas that make the program more useful.

**Comment by ngocnguyen83** [comment]
There is no gap between tiles and the wall.

**Comment by jondisla** [comment]
Wow from all the proposals I've read, yours is the most complex, I hope you will have enough time to finish it and I think you will.  I look forward to testing your tool,   I've never seen a program like this.  Great job!

**Comment by ngocnguyen83** [comment]
One more example to see how the program works. Inch is unit. 
Room's length: 10  
Room's width: 10  (So this room is a square). 
Tile size:   3           (We just need one size because we assume tile is square)
Tile gap:  0.05       (the distance between tiles. No gap between wall and tile):     
-------------------------------------
OUTPUT
Full title needed:     9
Reduced width tiles needed: 6  of size 3 x 0.4
Reduced length tiles needed: 6  of size 3 x 0.4
Corner tiles needed:        4 of size 0.4 x 0.4

Note: The program can take in the price for each tile and calculate the total cost.

**Comment by halfaro1** [comment]
@ngocnguyen83 I love this! As someone that's going to be tiling a 🏡 soon, this is very useful. As long as you're comfortable with these concepts I am comfortable 👍 

I'd suggest starting with a first version that does the program as you described in the original post (that's the one we'll use for grading). For version 2 (if you have time after you finish version 1), you could add the pricing information. For version 3, you could draw some ASCII art of what the room would look like with the tiles.

This is approved but I'm leaving it open for another day or so so that other students can get a look. Feel free to begin your design document and begin developing.

**Comment by smoussadeq** [comment]
Ngoc,
This is one of my favorite project so far. It really complex, but seems like you know what you are doing. The examples you provided really help of understanding your project.
Wish you the best of luck!

**Comment by ngocnguyen83** [comment]
I feel that we are having a great learning experience by implementing our ideas and give feedback for each other :star:
