### ISSUE TITLE
ryby6969' Final Project Proposal

### ISSUE THREAD

**Issue by ryby6969** [valencia-cop1000-201620/final-project#4]
### Name
Roy Davis
### Proposed Project Description

Magic 8 Ball
Ask the user their name
Request the user to ask the Magic 8 Ball a question
Give any of 8-? possible responses
Give an ability to exit the game

8 possible responses:
It is certain
It is decidedly so
My sources say no
Outlook not so good
You may rely on it
Ask me again later
Concentrate and ask again
Outlook good

Sample interaction:
Ask the Magic 8 Ball a question.
Will I win the lottery?
Concentrate and ask again.

### Connecting Concepts
I will use functions, flow control, among others I believe.

### Timing
I believe if approved I could get the project done in time. If approved by Tuesday I could potentially have it done on Tuesday as it is my day off. Otherwise I would be done no later than April 26.
### Asking for...
How many responses to use if not the traditional 8 as well as potential responses.

**Comment by halfaro1** [comment]
@ryby6969 good start on the proposal -- let's use the time you're scoping this out to think about what the responses would be. What would the interaction look like from the user's viewpoint? It could help your design to post a sample interaction.

**Comment by xyngabo** [comment]
Will the answer given be completely random or have something to do with the input given?

**Comment by ryby6969** [comment]
@xyngabo It would be completely random since that is how a traditional magic 8 ball works.
@halfaro1 I was thinking something like "Ask the Magic 8 Ball a question." The user would ask a question and then one of the generic responses would be printed.

**Comment by cholbrook2** [comment]
Just don't forget the "Ask me again later" lol, the standard response I always seemed to get. Maybe you could print an ASCII 8 ball to the screen in the beginning! Something silly, but an idea :)

**Comment by xyngabo** [comment]
Oh ok, Chapter Four has an example of a magic 8 ball. I made a similar program for android a while back.. Good luck =)

**Comment by ryby6969** [comment]
Oh wow, I knew I read something about a magic 8 ball program but wasn't sure where I seen it. I thought maybe it was in the Python book I had bought to help me.

**Comment by ryby6969** [comment]
I went back and looked at it and the one I want to code will look different than that one.

**Comment by halfaro1** [comment]
Great collaboration, everyone!
@ryby6969 Go ahead and edit your original post with the 8 possible responses, and a simulated set of user/computer interactions. When you do that I'll be ready to approve.

**Comment by Ldesir05** [comment]
At first i was unsure what the magic 8 ball was do you think you have enough time to complete this and are the answers going to be randomly populated. Hope to see this in action

**Comment by jashhhhhhh** [comment]
Sounds like an awesome program! 8 responses will be plenty and the code should be able to be completed within a weeks time! Great work!

**Comment by ryby6969** [comment]
Yeah, the answers will be randomly selected.

**Comment by nhatnam113** [comment]
Wow great idea! I can see a lot of people in our class making games. I'm so excited!

**Comment by jondisla** [comment]
Awesome! I always wonder if the magic eight ball knows something I don't know :8ball: I think your proposal is great.

**Comment by halfaro1** [comment]
@ryby6969 this is approved. I have a few suggestions though:
- make sure you use function; I don't have an issue with the simplicity of the program as long as it's original and properly applies what you've learned
- make sure your design document contains a high-level overview of the functions you will use, and how they will interact with one another
- consider adding one "wow" element to your project. An example of this would be figuring out when a user types in a special question (Will I win the lottery today? for example) and maybe formulating a witty response just for this type of question.
- get started with the program as you described it (make that your first version) and add the "wow" functionality to it in a later iteration

**Comment by halfaro1** [comment]
@ryby6969 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
