### ISSUE TITLE
Ian Miller's final project proposal

### ISSUE THREAD

**Issue by imiller6** [valencia-cop1000-201620/final-project#40]
Name
Ian Miller

 Proposed Project Description
For my project I was thinking of a sort of trivia game that gives you a score at the end. For this specific trivia game I would have it ask questions about my favorite sport, Formula 1. If you didnt know this is a motorsport and my program would ask questions about drivers and there stats as well as basic rules about the sport.

Connecting Concepts
It will cover most basics. Loops , variables, input , and lists.

 Timing
4/20 submit idea
4/23 complete draft
4/26 submit final

Asking for...
Should my questions be multiple choice? Or a mix of multiple choice and T or F.

**Comment by digitalBeast** [comment]
I think multiple choice questions should be the better option, for many who likes to choose what they like best in each questions.

**Comment by halfaro1** [comment]
@imiller6 what would your questions look like? I'd like to see all the options for sports and trivia questions before this is approved. 

I'd also caution you to make this different enough from @marcialsegura's (see #33). I know the questions are different, but I'd like you to have a different enough idea and gameplay to begin with so that you project can shine for all its awesomeness 🌈

**Comment by halfaro1** [comment]
@imiller6 how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by JoetheJedi** [comment]
I think true or false would make guessing too easy! Multiple choice seems like the way to go. I
m curious, when the user picks a incorrect answer will the program list the correct one after the input is received?

**Comment by halfaro1** [comment]
@imiller6 You received this score because your proposal was either (a) submitted late, and/or (b) you did not respond to feedback of your proposal in time to get approval before the due date.
