### ISSUE TITLE
DigitalBeast's final Project Proposal

### ISSUE THREAD

**Issue by digitalBeast** [valencia-cop1000-201620/final-project#42]
Final Project Proposal

### Name
Brian Torres = digitalBeast

### Proposed Project Description
My ideas of a simple python project list: 
Hangman
Navigation address system
BestFriend 
 Chess

**Hangman:** This project will become similar to 'guess the word' game, It is called 'Hangman'. This game is quite simple and might just take no longer then 2 days maybe or more. This game generates a word and must guess a letter to complete the word to win. If you guess the letter wrong piece of the hangman will appear giving you chances to still get the word right. I find this pretty straightforward and simple too. This hangman project might have a category list for you to be  interested in a type of thing, object, place, person or anything you may think of. 

Bestfriend: This project is the easiest to make as I think it is and it is to be as simple as 'hangman' and a popular game called adventure. Simply the computer is your best friend and you make a social conversations with it. Similar to those simulators game of ' talking monkey'. 

Many ideas to think of but, I am sticking with either hangman or bestfriend just because they are fun and simple programs to play with. 

### Connecting Concepts

The hangman game will contain many of the basics we all have learned. Which are:

Multi-line Strings
Methods
Lists
The append() and reverse() list methods
The range() and list() functions
del statement
for loops
elif statements
The in and not in operators
The lower(), upper(), split() startswith() and endswith() string methods

### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates.
Once my approval is updated, depend how quickly I fix errors and running the project smoothly

 I'll start gathering the codes from the python chapters, 4/21. 
apply the codes together including the designs 4/23.
Structure the codes together and understand each code functions together in their proper place 4/24.
Test it and fix any bug and see how the program runs and will be finished by 4/25 or 26.

### Asking for...

What are your opinion on this project? maybe a better project or make few changes to this project.

**Comment by halfaro1** [comment]
@digitalBeast hangman is very popular, so I'm going to suggest you go with Best Friend. However, I'd like you to explain that a little further. What kind of conversations can the user have the computer? Start by listing out some questions and possible responses. I'd also like to see a plan for how you'd like to deal with the user entering varying forms of the same response.

**Comment by ukates** [comment]
The best friend idea is pretty neat, i agree with @halfaro1 on the fact that you would need to think of something to do if someone kept asking the same thing over and over again.  I'm not really sure how you would do it, maybe some sort of if statement possibly? Like if the user asks this question or inputs this string (maybe like a key word or phrase) then the best friend will return something like "you already asked me that, think of something new" or something like that.  or maybe you could have the best friend suggest a new topic at the end of each answer or response.  Im not much help with implementation but these ideas could be cool.

**Comment by digitalBeast** [comment]
@halfaro1 Understood, so the game 'Best friend', will have the user and computer to interact with eachother. They both will have conversations of up to 3 topics; sports, video game, and mythology or a different option of topic. Each topic will lead on until the computer runs out of something to say so computer will try to lead the user to another topic.  The reason why only 3 is because of the amount of time I have to think of how the conversation should turn out depend on the user's answer. So lets say the program run, it will start off the Computer to say one word at a time to actual have the user think the computer talking to him/her. "Hi I am your imaginary best friend from childhood! how are you!". Then the user response will say something like "Hi I don't remember having a imaginary friend.." then the computer response back, " Don't worry you may not know me, but I been your bestfriend helping you with your homework and stuff!". Then the conversation continue from their. If the user wants to end the conversation they can say "bye" or "don't talk to me you creeping me out" then the computer will be say something like "Alrighty that's cool just wanted to see how you doing! need anything or google something I'll be right here" then they give you the option "end game" and the program end. The program will still run unless you type end game to end it entirely. So, I'll have various tree of conversations to put together by using the true and false statement and many if, or, and elif statement and other useful method  to create this.

**Comment by halfaro1** [comment]
@digitalBeast alright, I like the idea of best friend.

My suggestion would be to limit the number of responses the human user can enter. So an example interaction would look like this:
```
💻 : Welcome! How are you? [possible responses: `good`, `bad`, `ok`]
👱 : ok
💻 : Just ok!? I'm your imaginary friend. Remember me? [`yes`, `no`, `maybe`]
👱 : yes
💻 : You're not well in the head, are you?
```
Make sense?

**Comment by digitalBeast** [comment]
Yes That is the exact example of the program I am picturing for this project. with the Icon and response as well :)

**Comment by halfaro1** [comment]
@digitalBeast alright please make sure you have the conversations planned out in the design document with the possible responses.

**Comment by digitalBeast** [comment]
And when you design document do you mean the structure of the program or just a paper about the program? because I will write down on paper of how the program going to look so that way I don't lose track on how this project will work.

**Comment by JoshuaRi** [comment]
I like the idea of being able to talk to a program and seeing what it says, seems like something you can do easily in a weeks time while adding many different dialogue options to the program.

**Comment by halfaro1** [comment]
@digitalBeast the design document should be a written description of your program structure and logic

**Comment by halfaro1** [comment]
@digitalBeast I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
