### ISSUE TITLE
flacks' final project proposal

### ISSUE THREAD

**Issue by flacks** [valencia-cop1000-201620/final-project#43]
### Name
Jean Lucas

### Proposed project description
I am undecided from a few ideas, these being:
- Password generator/safe/export
- Hangman (simplest to fall back on)
- Language translator using API

**Password generator/safe/export**
This program would serve primarily as a password generator similar to `pwgen`, though considerably weaker in security and randomness. It would also double as a password safe, by storing a program safe file in either the user's home directory or in the directory where the program files are located. Despite the weaker math for password generation, this program would not be intended for daily usage, as it is a project, unless some harder logic were to be implemented into it later. This program would be interactive, prompting the user for the desired length of the password if no other arguments are provided, or parse options passed to it in the manner pwgen does for the password generation function. To illustrate an example of how pwgen parses options, `pwgen 64 4` generates 4 64-alphanumeric passwords. The program would then prompt the user for labelling the password if it was desired to be kept, then ask if the password should be saved to the program safe, or if it should be appended to an existing file somewhere else, taking care not to overwrite the destination file by making a copy of it first. If a password was chosen to be saved to the program's safe, the safe file would be generated, and upon rerun of the program, this file would be detected, and the program would switch to a mode prompting the user for viewing any of the stored passwords by label.

**Hangman**
This would be a guessing game pulling a dictionary from some place on the internet or from an internal dictionary, where the user is simply prompted for letters matching to the word, and the rest of the rules being identical to that of a typical hangman game.

**Language translator using API**
I'd like to take this on, as I constantly translate languages, and would like something native and extensible that can be integrated into my system very nicely, preferably written by myself. This program would use an API by a service that allows for no account/key, such as http://mymemory.translated.net/. The program would likely be a simple English to Spanish translator, maybe also working in vice versa, maybe a wider variety of language choices, depending on how difficult it is to implement one selection.

### Connecting concepts
The password generation program would draw upon random characters, user input, and reading/writing to files; hangman would draw upon scraping the internet (potentially), manipulating strings, and user input; and the language translator would draw upon scraping the internet and dictionaries/structuring data.

### Timing
I'm hoping to take less than a week to implement any of the above ideas. I would go over the course textbook again as well as find any resources needed online, and implement everything with my own code. Tasks include research, research, and research. The translation program requires an API, so I'd study the mechanisms it provides for python, and work towards implementing some basic functionality with it.

### Asking for...
Any feedback is welcome... I'd prefer some realistic time frames and difficulty levels, since I'm biased towards coolness of the projects, as I think I'd use them. One week is a considerably short amount of time for something involved. Any recommendations for things to add or remove to decrease estimated time frame and difficulty are welcome.

**Comment by halfaro1** [comment]
@flacks thanks for the attention to detail and all the options 😄 

It look like we already have quite a few hangman ideas, and one password generator idea (see #13). So I'll suggest you work on the translator. However, I think you have a valid point about keeping it simple enough to implement in one week. So I'd suggestion making your submission a "version 1" with the goals of (1) successfully making 1 call to the API. You can shape the user interaction around that one, simple call to the API. This way you can set yourself up for success, and anything else you can do is icing. For example, your program could have the stated purpose of translating single words form English to Spanish. 

Possible version 2 (but not required for credit) could be allowing the user to select from a limited list of languages, and translate a single word from English to the chosen language. Possible version 3 could be allowing the user to select the source language AND the destination language. 

How do you feel about it? Classmates, looking for your feedback too.

**Comment by aeuteneuer** [comment]
Jean,

It sounds to me that you have some programming experience. Either that or you are a very fast learner! Anyway I think if you successfully can make the API call you could for instance type a word in english and that word would be returned in Spanish.  I think that could be implemented within a week.

**Comment by flacks** [comment]
@aeuteneuer Thank you for the support. I have been programming for some time now. This ought to be an interesting project because in the end it should integrate seamlessly with an OS, and it'd be nice to document that so you and others could do so, too. First revision should indeed take less than a week.

@halfaro1 Thank you for the feedback, professor. I'll work on your suggestions and try to get this done soon.

**Comment by halfaro1** [comment]
👍 awesome

**Comment by halfaro1** [comment]
@flacks I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
