### ISSUE TITLE
Richard Tran Final Project Proposal

### ISSUE THREAD

**Issue by rtran4** [valencia-cop1000-201620/final-project#46]
### Name
Richard Tran

### Proposed Project Description
In this project, I will be creating a connect four game between 2 players. It will run in X columns and it will take turns between the players by the first letter red and yellow. They will input a number from 0-6 when prompted and a connect four piece will drop down based on their player's color. When a player reaches a goal of 4 in a row vertically and horizontally it will prompt a winner! 

### Connecting Concepts
I will be needing functions and lists so chapters 2-4.

### Timing
This project will take me about a week or less to code. I have already started and have my ideas. 

### Asking for...
Some rules of connect four I may be missing or that I can implement maybe?

**Comment by halfaro1** [comment]
@rtran4 thanks for the suggestion! There is another Connect Four game (see #23) so I'd like to suggest you modify your game a little bit so that it's different enough.

**Comment by halfaro1** [comment]
@rtran4 how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by AustinBarnett** [comment]
I think that showing when a row is filled to the top would be a cool feature to include in the program.

**Comment by halfaro1** [comment]
@rtran4 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
