### ISSUE TITLE
My Final Project

### ISSUE THREAD

**Issue by Tchomp** [valencia-cop1000-201620/final-project#49]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

Timothy Swain

Hello, I plan on doing a text-based adventure in which the player chooses concrete options to travel down difficult pathways. This text-based adventure will utilize several files and sequences depending on actions that are shown to the player. Most of the project will be based on inputs, multiple sequences, running files other than the initial program, and the basic print program. 

At best, I hope the project to of course utilize the print option, but to utilize multiple files in order to make it shorter, so when certain sequences come to a close, then it will start running the next file based on certain inputs described to the "Player" or whomever is running the program. 

I honestly don't know how long it will take considering I've never written a purely unique program based on the concepts in my mind. I want to say two weeks at the best, but I would attempt to finish it in one week. 

Occasional pieces of advice when certain problems come to light in the program is all I would need. This isn't a overly complex project, just an overly large one with particular details that need to be regulated.

**Comment by halfaro1** [comment]
@Tchomp great idea! However, there are some other text adventure games (see #37 and #12). I'd like to make sure yours is original enough to be set apart and be awesome on its own. What features can you add to your game so that it is set apart?

**Comment by halfaro1** [comment]
@Tchomp how are you doing on this? the final project is due soon so I'd like to help you move forward quickly.

**Comment by Tchomp** [comment]
I was planning on it being a text-adventure with RPG specific aspects, where the decisions of the player show over time. And the program analyzes previous coding results based on their actions.

**Comment by halfaro1** [comment]
>And the program analyzes previous coding results based on their actions.

@Tchomp what does this mean?

**Comment by nickivey2** [comment]
I have worked on RPG projects in the past, sounds good! The best thing about adventure programs is you can reuse code to create similar scenarios. Running external programs sounds interesting, what programs will you be executing?

**Comment by JohnSwain117** [comment]
I think he just meant that he'll reuse some functions or variables. Or that he'll make events that only trigger if you take a specific route

**Comment by halfaro1** [comment]
@Tchomp how are you doing on this? While making sure you have a unique theme does make your idea unique, it does not make your programming unique. For example, I could (in theory) find a text-based game in the horror genre, keep the same code, but change the content so it is comedy genre. What I'm after is what unique flavor you'll give to your code that makes the program only yours. The goal here is to help you craft something you'll be proud of.

**Comment by Tchomp** [comment]
Right now, the project was formatted to be a text-based game that reflected upon choices. Like JohnSwain117 said, it is meant to allow one to make a specific route.

**Comment by Tchomp** [comment]
Unfortunately, I had originally planned to implement boss battles via long lines of branching variable coding and input. However, under realization of time, I stepped back a bit and used more of a puzzle aspect and chose to go along a pathways through the variables, as such, some pathways are longer than others, some have more or less choices, but all of the pathways have one or two similar features in order to keep a general idea about what is needed to be done.

**Comment by halfaro1** [comment]
@Tchomp I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
