### ISSUE TITLE
aeuteneuer Final Project

### ISSUE THREAD

**Issue by aeuteneuer** [valencia-cop1000-201620/final-project#50]
### Name
Alexander Euteneuer

### Proposed Project Description
For my final project I would like to make a text based program similar to the popular mobile application "Lifeline". The program will offer the user a series of choices and depending on what they choose, determines the outcome of the story.

### Connecting Concepts
What chapters/topics will this project allow you to practice? A good final project will cover at least 2 distinct topics from class.

This application will utilize a couple practices from the book.  The first would be functions (Chapter 3).  I plan on programming this so that any potential answer calls a new function and the program would continue that way until it ends. The second practice would be manipulating strings (Chapter 6). Depending on what the user selects strings will be manipulated from the answers.

### Timing
How long do you think this project will take to implement? Feel free to give a brief timeline of tasks you'd like to accomplish with dates. 

I think with the different outcomes I would like to implement, the task at hand should be completed no later than 4/25/16.

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful?

I would like to know what type of story the class would like to see for a program like this.

**Comment by halfaro1** [comment]
@aeuteneuer since this is due next Wednesday, please start creating at least a draft story and post that here, along with the choices. Be careful with the many other adventure games that are proposed, so think about what might make your program unique. In the case of Lifeline (very cool game, by the way!) I think one of the elements that makes it interesting is that it doesn't have to be played all at once, and events happen throughout the day. Could you somehow implement something similar?

**Comment by aeuteneuer** [comment]
I could try to implement something similar to that with the user able to come back and continue.

**Comment by aeuteneuer** [comment]
Since this is due this wednesday I would like to get approval so I can push forward.  You asked for a draft of all the story and choices but that will come as I code.  I can provide a final draft with the final project if requested. Please let me know if I have your okay. Thank you

**Comment by halfaro1** [comment]
@aeuteneuer creating a story is part of your design and scoping, not so much the coding. I want to avoid you coding "as it comes" and want to encourage you to plan ahead. Also, please realize that you opened this issue just a couple of days ago and the proposal was due last Wednesday, so you'll have to move quickly to meet the deadline.

**Comment by aeuteneuer** [comment]
This is a draft of a potential scenario a user could run into by making choices.  The bold indicates the selected choice. 


It was just a normal day.
I was on the app store when I came across a radio tuner application.
My friend told me you could listen in on different types of signals.
So I decided to download it and give it a try.
That's when this happened…

*static*
…
…
…
Hello?!
Hello is anyone there?


Choice # 1

**1.) H-Hello**
2.) I am here. Who is this?

…
… oh thank god!
Seriously. Thank god. I have been trying to get ahold of someone for 4 days!


Choice # 2

**1.) Four days!?**
2.) Where are you?

Yes. I have been stranded on this island…. my plane crashed….

Choice # 3

1.) Plane...what plane?
**2.) An island? Can you be more specific?**

I really can’t. The plane crashed and I barely made it out alive. I was floating on a piece of debris and just woke up here.

Choice #4

1.) Okay well what is around you?
**2.) You are lucky to be alive!**

Tell me about it. I believe my plane was somewhere over the North Atlantic before the accident happened.

Choice # 5

**1.) Accident? What accident?**
2.) Are there any other survivors?

…to be continued…

**Comment by AustinBarnett** [comment]
I think the direction of the project is great! Maybe adding some sort of random outcome generator to the last two choices will truly make it so outcomes are very unlikely to be the same.

**Comment by halfaro1** [comment]
@aeuteneuer I like how this is shaping up - please keep moving forward!

**Comment by halfaro1** [comment]
@aeuteneuer I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
