### ISSUE TITLE
Adam Perez Final Project Proposal

### ISSUE THREAD

**Issue by aperez259** [valencia-cop1000-201620/final-project#54]
### Name
Adam Perez

### Proposed Project Description
I will create a Who Wants to be a Millionaire game, where a player will be asked a question and be given 4 possible answers from A through D. If the player answers the question Correctly, then he will move on to the next question. There will be 2 milestones, after the 5th and 10th question, so if the player answers it wrong they will still get some money ($1,000 at the 5th, $32,000 at the 10th)

The player will also have 3 lifelines that can only be used once in the whole game, which will be 50/50, where 2 wrong answers get removed. Ask the expert, where the expert will give his insight on the question (will have a 75% chance of being right). and also double dip, where the player can choose 2 answers for that question.

The player will have the option to quit and take his earnings in the middle of every question.

If the player gets through the 15 questions, they will win the grand prize of $1,000,000!

Also, the higher you go in questions, the more difficult the questions become.

### Connecting Concepts
Lists chapter, Functions chapter and the Flow Control chapter

### Timing
4/25 get approval for the project.
4/27 Finish and turn in the completed program.

### Asking for...
Anything that you believe would help me improve the game!

**Comment by halfaro1** [comment]
@aperez259 awesome! And I love how you've thought through this and described how you could modify some of the characteristics of the actual game for use in a computer program. This is approved, but I'll suggest you implement this in versions. Version 1 (and the only one required for credit) would be to implement a game capable of asking a series of questions with the betting and milestones features. Version 2 would then implement some of the other features you described, maybe you could implement one lifeline at a time? I'm leaving this open to allow other people to give you feedback, but please start your design by posting the questions you'll use for your game here.

**Comment by JoetheJedi** [comment]
This is a great idea! Are you making the questions yourself or integrating some of the actual game show questions? If you use some actual questions this could be some good practice for anyone planning on participating in the actual show haha

**Comment by Tchomp** [comment]
Interesting. It sounds as though the code will be branching quite a bit, but it sounds incredible when achieved. I look forward to the content produced by this, as it must be a great stress reliever while working through the python coding of the project.

**Comment by halfaro1** [comment]
@aperez259 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
