### ISSUE TITLE
jnoriega3 Final Project Proposal - Word Scramble Game Special

### ISSUE THREAD

**Issue by jnoriega3** [valencia-cop1000-201620/final-project#59]
### Name
Jessica Noriega

### Proposed Project Description
I would like to create a word unscramble game where the user will be given a word that is scrambled out of order  and they will need to unscramble the letters to guess the word. After user input, they will find out if they guessed correctly or not and then be given the option to continue playing or end the game. 

### Connecting Concepts
Chapters 1 through 5 will be used for practicing Python Basics, Flow Charts, Functions, Lists, Dictionaries and Structuring Data, and Manipulating Strings. 

### Timing
4/24 & 4/25 - Pending Project Proposal Approval
Plan/Brainstorm the project and user interactions as well as variation ideas of the game for a unique project
4/26 - Practice run and feedback
4/27 - Submit Final Word Scramble Project

### Asking for...
What would you like to see in this word scramble game to make it different and not boring? Maybe a theme? Any extras to include? Please feel free to send me any ideas or suggestions for this program.

**Comment by halfaro1** [comment]
@jnoriega3 this is a great proposal. Can you post some examples? Then I'll be ready to approve.

**Comment by elisenharper** [comment]
Will it just be one word or could you make it a phrase? That might make it more challenging for the player

**Comment by AustinBarnett** [comment]
Maybe making the word scramble words in the end make out a sentence that connects back to the class!
Love the planning though very well thought out!

**Comment by jnoriega3** [comment]
@halfaro1 examples of this scramble game would be something like prompting the user with Information about the game and if they would like to play they will be asked to press yes or no or enter to quit.

At the start of the game, they are given a word or words scrambled and they need to guess the word. It's just a brain teaser game to keep your mind thinking. I am planning to stick to a Python Programming Themed words. There are not too many exciting variations for the game that I have been able to come up with, but maybe its something I can work on long-term for practicing the lessons learned in the book.  

Please let me know your thoughts.

@elisenharper Thank you for your comment, I thought it was a great idea and definitely more challenging as a phrase so i started planning out my game that way.

@AustinBarnett  I really liked your idea of making it into a sentence that connects back to the class! Then I was thinking of the details and maybe I was getting way too detailed because I think it gets tricky. I think i'd only be able to make one sentence in my game because if i had several sentences the words would get shuffled between sentences as code selects words from the whole list at random and then it would be one big scrammbled sentence.   

Thank you for the great ideas I will be using in my program!

**Comment by halfaro1** [comment]
@jnoriega3 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
