### ISSUE TITLE
abigailanderson final project proposal

### ISSUE THREAD

**Issue by AbigailAndersonn** [valencia-cop1000-201620/final-project#6]
Name

Abigail Anderson

Proposed Project Description

For this project, I would like to make a program that will be able to tell me a persons birthday and possibly how old they will be turning. The program would ask for a name from the database (dictionary of family members) and return a string containing the persons birthday and age. To get the ages I will need to write code that will subtract the birth year of each person from the current year (2016) and print the result. I haven’t decided if I want to do a list of names and an integer input(since there will not be too many) or ask for a written name. 

Connecting Concepts

I will be using concepts learned in chapters 2 - 6 from the textbook. Such as dictionaries, operators, flow control statements, and functions. I will also be using the datetime module.

Timing

I feel like this project will not take me more than a few days to complete. I’m sure I’ll be able to have it ready at least on time.

Asking for…

I would appreciate any tips or advice on how to go about any of this, nothing in particular. All options welcome! haha

**Comment by cholbrook2** [comment]
This is a really good idea! I usually end up using Facebook to remember birthdays :X I think you should use the written names! Seeing as this could be something you could actually use later on if you needed to!

**Comment by AbigailAndersonn** [comment]
awesome, thank you! I can usually remember birthdays but not ages, haha. do you think I should do a dictionary type data base for the names or if and elif statements? I think the if and elif statements would be easier to add on later like you said.

**Comment by AbigailAndersonn** [comment]
and would it be appropriate to just change the current year in the actual script each new year or should I incorporate it into the program now. for example, having the current year be an input.  Which could be cool to see the age in future years, but take away some of the convenience.

**Comment by Lamle104** [comment]
Awesome idea! I had something similar in mind as well. :)

**Comment by halfaro1** [comment]
@AbigailAndersonn good start, but you'll run into the same issue as @Lamle104's program (see pull request #5). Might I suggest for your program that you modify it a bit so it just calculates someone's age based on their birthdate? That will make it different enough and it will also save you the trouble of having to figure out how to save data in a file or database. Let me know what your thoughts are.

**Comment by AbigailAndersonn** [comment]
Yes, I will do that! would I have birth year input and just have it subtracted from the current year?

**Comment by Ldesir05** [comment]
this is a very good idea for me it very hard to remember birthdays and i tend to go by social media for friends and family birthdays good luck

**Comment by halfaro1** [comment]
@AbigailAndersonn glad to hear we were able to find a middle ground :) you have options for how you can do this, and I would suggest you enumerate those options before you start implementing. Here's two ways I can think of you doing this:
1. You can do calculations based only on the year -- this is inaccurate because it won't take into account if someone's birth month has passed or not.
2. You can do calculations based on exact birthdate -- this is more accurate, but may not account for leap years.
3. You can do calculations using a built-in Python library. I suggest you do this! Can you look to see if there is a Python library you can use that will perform date calculations for you? I'd like you to do this before we close the request as approved. If you find one, go ahead and edit your original post with that information and let me know in a comment so I can approve.

**Comment by AbigailAndersonn** [comment]
I updated it with my decision to use the datetime module for this program.

**Comment by shuroq** [comment]
Nice idea!! everyone will need that definitely. I have a lot of friends and it is too hard for me to remember dates. Good luck in your project :)

**Comment by halfaro1** [comment]
@AbigailAndersonn great, this is approved 👍 don't forget to create a design!

**Comment by halfaro1** [comment]
@AbigailAndersonn I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
