### ISSUE TITLE
elisenharper's Final Project Proposal

### ISSUE THREAD

**Issue by elisenharper** [valencia-cop1000-201620/final-project#8]
### Name
Elise Harper

### Proposed Project Description
I would like to write a program that gathers the newest 5 pictures from my company's Instagram page and opens them in different tabs on your browser. I work at a television station (Fox 35) and I frequently have to scroll through our social media pages and take screenshots of our postings to share with our advertisers. If I could write a program that would just open that last 5 photos in different tabs then I could quickly go through and make screenshots to send in email.

UPDATE: I had to modify my program a bit once I started actually coding. As expected, pinpointing the actual html code for the pictures on Instagram was very difficult. This made it very hard to open the pictures in different tabs. After extensive Google searching and reading blogs for answers, I discovered a bunch of cool things that you can do with the Selenium module. I realized that may be the perfect work-around for what I'm trying to accomplish. So I've modified my program to do the following: open a Firefox browser to Google, search for the term 'Fox 35 News Instagram', click the link for Fox 35's Instagram page, take a screenshot of all the pictures shown on the first page, save that screenshot to the current working directory and then close the browser. The biggest difference is the pictures won't open in different tabs but I can now get a screenshot of them to automatically save to my computer.

### Connecting Concepts
This project will refer heavily to the web scraping chapter as well as the chapter about organizing files and folders. I plan to use Firefox as the web browser. I'm also utilizing the Selenium module to control the web browser.

### Timing
Realistically, this project will probably take about a week once I start writing the code and then testing it. One issue I can foresee is that every time I run the program, I'll more than likely get a different set of pictures since the Instagram page is constantly being updated. My goal is to do the majority of the coding over the weekend when I have several hours to dedicate to the project.

### Asking for...
Any tips that would be helpful when it comes to web scraping and working with pictures. Figuring out the pictures' element id on Instagram will probably be challenging. Thanks!

**Comment by AbigailAndersonn** [comment]
Maybe you could set up a test Instagram account to figure out the basic code and then replace it with the company account? That would at least help keep the test results consistent and save you a bit of trouble, I think!

**Comment by sabbott7** [comment]
The internet can be a unreliable environment in which the connection may be lost (or become very slow) at any time. Due to that, I would say it’s a good idea to break all your data to be loaded into separate pieces to be "scraped" separately (of course, they may be loaded simultaneously). If some pieces of your data can’t be received because of the website or connection has been overloaded, then at least the other pieces are not influenced and you can safely save them for further processing.

**Comment by elisenharper** [comment]
Good advice! Thanks @AbigailAndersonn and @sabbott7

**Comment by halfaro1** [comment]
Awesome chat, folks! 
@elisenharper I love this idea -- it's very specific, you'll be able to put it to use in your daily work, and not too complicated. I think you can absolutely do this with web scraping. Another avenue is APIs (check out my comment on @cholbrook2's proposal #7) although in your case in particular you don't need to use an API but I just wanted to point it out to you so you know it's out there. Here's [Instagram's API](https://www.instagram.com/developer/).

I would also encourage you to use @AbigailAndersonn's idea:
> Maybe you could set up a test Instagram account to figure out the basic code and then replace it with the company account? That would at least help keep the test results consistent and save you a bit of trouble, I think!

This would let you test in a safe environment, and then you can switch out to your company's account. You have my approval to move forward with this!

**Comment by elisenharper** [comment]
@halfaro1 Thank you for the suggestion about the Instagram API. I've been looking into it and seems interesting but I think I would need more time to implement that. For this project I think I'll stick with the web scraping elements that we've learned but I like tinkering about with new things so that's something I'll check into!

**Comment by halfaro1** [comment]
@elisenharper I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
