### ISSUE TITLE
AustinB's Final Project

### ISSUE THREAD

**Issue by AustinBarnett** [valencia-cop1000-201620/final-project#82]
**Please change the Title of this issue to include your username, something like: halfaro1's Final Project Proposal. When you've done that, you can remove this line and fill in the rest of the body of this issue below.**

### Name
What's your real name? Austin Barnett

### Proposed Project Description
For my final project I would like to do something with a magic 8 ball. Growing up I have always been interested in it, but now of course I know better. In my program I would like to make a program that will ask the player to ask a question about whatever they want. Following that I want to program to give a random response. One thingI want to learn how to add is a way to make the program answer slowly as if the play actually was shaking the 8 ball.

### Connecting Concepts
What chapters/topics will this project allow you to practice? A good final project will cover at least 2 distinct topics from class.
This project will help me practice the random answer generator and help me build a program that gives a response off of a random choice. 

### Timing
I think that this project should take about three days to make since I will have to find the necessary parts for importing and coding something to delay my responses. 

### Asking for...
What kind of feedback can your classmates and professor provide to help you be successful? What can I add into this program to make the feel a little more special?
Is there a type of background I could get the program to open to build the atmosphere? 
Should I make a magic 8 ball that always gives negative or positives responses?

**Comment by halfaro1** [comment]
@AustinBarnett thanks for the proposal. The Magic 8 Ball has already been proposed in #4. What else could you do that's similar but not the same?

**Comment by AustinBarnett** [comment]
Could I possibly keep the magic 8 ball but put a twist on it so there is two options, maybe have the person have two options
one option begin 
"Are you looking for the truth or lies?"
if truth then only give positive responses 
if lies then only give negatives responses 
so it turns into a magic 8 ball for emotional support?

**Comment by AustinBarnett** [comment]
I made a new program as an emotion reader where i ask a series of questions and then at the end give a random answer on how their emotional state will be by the end of the night

**Comment by halfaro1** [comment]
@AustinBarnett ok, what do those series of questions look like, what's the random answer based on the emotional state?

**Comment by AustinBarnett** [comment]
The question would be
How has your Day been
Are you thinking about something from today?
Who was one person you wish you spoke with today
did anything out of the ordinary happen
have you had any regrets today
what is your age

the question i chose would make people think about some of the basic things that more than likely had some type of impact on almost anyones day and then adding their age would make them feel a little more engadged

I want my answers to be similar to a magic 8 ball in that they are vague and not really based off of anything because i want this to be able to be used easily and universal and almost all answers would have an emotion that happen quite often.

**Comment by halfaro1** [comment]
@AustinBarnett ok, it's a starthow can you add complexity to this project so it covers perhaps multiple chapters in the textbook?

**Comment by halfaro1** [comment]
@AustinBarnett I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Comment by AustinBarnett** [comment]
Thank you for everything professor and all the support have a great summer!
