### ISSUE TITLE
elicegreen's Final Project Proposal

### ISSUE THREAD

**Issue by elicegreen** [valencia-cop1000-201620/final-project#9]
### Name
Elice

### Proposed Project Description
Card Game War
Two players (user and computer) have 23 (half a deck) each. Each in their turns flips the top card of their deck. The player with the higher value card takes both cards. If the two players flip the same value card, each player has to draw three more cards and the player with the higher value card for the third card flipped takes all cards.
I just finished playing it with my son last night before sitting down to think of a project and then realized that I could probably write code for it.
So far I know that I'll need to use at least 'lists' to store each of the opponents dealt cards. But will explore using dictionaries so to store numerical reference to all cards for easy value comparison. 
I'll also have to randomize the card selection but within the option a deck of card would offer.
As I work on this I will determine whether or not to make it a one 23 move game, announcing the winner according to whomever gained the total highest value of cards after going once through each players cards; or if I'm going to stick to the original, allowing the game to continue until one player is left with no cards. This of course will depend on how hard it will be to code the latter :-P
I don't know if any of what I wrote here makes much sense. I tend to understand things better as I get my hands dirty with the actual code.

### Connecting Concepts
Flow Control, Functions, Lists, and maybe Dictionaries

### Timing
By 04.20 Create a general structure of the program
By 04.24 Create the entire program and submit it

### Asking for...
Not sure yet

**Comment by BobbyGatlin** [comment]
This is a pretty cool idea. I actually thought about doing something like this as well before I decided to go in a different direction. I'm pretty excited to see how this is implemented.

**Comment by mmarchetti2** [comment]
If you think you can pull it off, this would be a great final project! I'm trying to think on how I'd implement it, but if you have a general idea on how to do it, I think you'd have an awesome program to show off. :D

**Comment by halfaro1** [comment]
@elicegreen I think I understand what you mean by a card game of war, but could you write it in a little more detail? You can edit your original post if you like.

**Comment by pvo4** [comment]
I think a card war game is an awesome idea, however it sounds difficult to implement within the time frame. If you have an idea on how to do this, I would love to see the finish project. If I may suggest, if it's possible maybe make a program that opens up and plays the card game from a website.

**Comment by Ldesir05** [comment]
this sounds like an interesting game i actually wrote one similar to this while learning x-code good luck :)

**Comment by elicegreen** [comment]
@halfaro1 Yes. I meant the card game of war.
I just finished playing it with my son last night before sitting down to think of a project and then realized that I could probably write code for it.
So far I know that I'll need to use at least 'lists' to store each of the opponents dealt cards. But will explore using dictionaries so to store numerical reference to all cards for easy value comparison. 
I'll also have to randomize the card selection but within the option a deck of card would offer.
As I work on this I will determine whether or not to make it a one 23 move game, announcing the winner according to whomever gained the highest value of cards after going once through each players cards; or if I'm going to stick to the original, allowing the game to continue until one player is left with no cards. This of course will depend on how hard it will be to code the latter :-P
I don't know if any of what I wrote here makes much sense. I tend to understand things better as I get my hands dirty with the actual code.

**Comment by halfaro1** [comment]
@elicegreen perfect thanks for the clarification. Please update your original post with the detailed explanation of what the game of war means to you and for the purposes of this program. One thing you're going to have to think about is how to store the deck of cards. Will your list have 52 different elements (one for each card?). And will they be represented by text? Or are you going to have some sort of image manipulation? There's no pressure to do images at all, I just want you to think this through.

**Comment by jashhhhhhh** [comment]
This looks like it could be lots of fun! Wondering if you would use a random number generating function to assign the cards to the players? This could make the game infinitely replayable!

**Comment by elicegreen** [comment]
@halfaro1 I decided to just use a list with the values 2-14 four times each. I will specify to the player before the game starts that in this game the number 14 represents the Ace.
@jashhhhhhh I will use a the random.shuffle method on the whole deck (list) before dealing the cards.
@pvo4 I think I'll manage to implement the game since I'll probably simplify it to a one round game (winner is whomever obtained the highest value of cards after going through the whole pile of 26 cards) rather than the original game that is played until one player is left with no cards.

**Comment by halfaro1** [comment]
👍 approved @elicegreen

**Comment by JoshuaRi** [comment]
Is there any chance you can add a computer to go against in this game? I think it would be a cool bonus.

**Comment by halfaro1** [comment]
@elicegreen I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:
